## ==> make -f Makefile.sample

INC_DIR   = ../../../../include
LIB_DIR   = ../../../../linux64
#LIB_DIR   = ../../../../macos64
#LIB_DIR   = ../../../../win32
#LIB_DIR   = ../../../../win64

CC_CFLAGS = -g -Wall
CC_LFLAGS = -loes_api -lpthread -lm

all:
	gcc $(CC_CFLAGS) -I$(INC_DIR) oes_client_sample.c -L$(LIB_DIR) $(CC_LFLAGS) -o oes_client_sample

clean:
	rm -f *.o oes_client_sample
