#!/usr/bin/env bash

export VNPY_TEST_MYSQL_DATABASE=vnpy
export VNPY_TEST_MYSQL_HOST=127.0.0.1
export VNPY_TEST_MYSQL_PORT=3306
export VNPY_TEST_MYSQL_USER=root
export VNPY_TEST_MYSQL_PASSWORD=
export VNPY_TEST_POSTGRESQL_DATABASE=vnpy
export VNPY_TEST_POSTGRESQL_HOST=127.0.0.1
export VNPY_TEST_POSTGRESQL_PORT=5432
export VNPY_TEST_POSTGRESQL_USER=postgres
export VNPY_TEST_POSTGRESQL_PASSWORD=
export VNPY_TEST_MONGODB_DATABASE=vnpy
export VNPY_TEST_MONGODB_HOST=127.0.0.1
export VNPY_TEST_MONGODB_PORT=27017

