#include <iostream>
#include <string>
#include <pybind11/pybind11.h>
#include <autocxxpy/autocxxpy.hpp>

#include "module.hpp"
#include "wrappers.hpp"
#include "generated_functions.h"

#include "TORATstpMdApi.h"
#include "TORATstpTraderApi.h"
#include "TORATstpUserApiDataType.h"
#include "TORATstpUserApiStruct.h"


void generate_class_CTORATstpTraderApi(pybind11::object & parent)
{
    pybind11::class_<
        CTORATstpTraderApi,
        std::unique_ptr<CTORATstpTraderApi, pybind11::nodelete>,
        PyCTORATstpTraderApi
    > c(parent, "CTORATstpTraderApi");
    if constexpr (std::is_default_constructible_v<PyCTORATstpTraderApi>)
        c.def(pybind11::init<>());
    c.def_static("CreateTstpTraderApi",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::CreateTstpTraderApi
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def_static("GetApiVersion",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::GetApiVersion
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("Release",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::Release
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("Init",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::Init
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("Join",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::Join
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("RegisterFront",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::RegisterFront
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("RegisterNameServer",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::RegisterNameServer
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("RegisterDeriveServer",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::RegisterDeriveServer
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("RegisterSpi",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::RegisterSpi
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("SubscribePrivateTopic",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::SubscribePrivateTopic
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("SubscribePublicTopic",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::SubscribePublicTopic
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqUserLogin",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqUserLogin
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqUserLogout",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqUserLogout
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqUserPasswordUpdate",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqUserPasswordUpdate
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInputDeviceSerial",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInputDeviceSerial
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqOrderInsert",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqOrderInsert
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqOrderAction",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqOrderAction
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqCondOrderInsert",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqCondOrderInsert
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqCondOrderAction",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqCondOrderAction
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryJZFund",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryJZFund
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqTransferFund",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqTransferFund
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqTransferCollateral",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqTransferCollateral
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryBankAccountFund",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryBankAccountFund
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryTradeConcentration",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryTradeConcentration
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryMaxOrderVolume",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryMaxOrderVolume
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryHistoryOrder",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryHistoryOrder
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqInquiryHistoryTrade",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqInquiryHistoryTrade
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryExchange",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryExchange
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryMarketData",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryMarketData
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQrySecurity",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQrySecurity
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryETFFile",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryETFFile
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryETFBasket",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryETFBasket
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryIPOInfo",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryIPOInfo
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryBUProxy",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryBUProxy
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryUser",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryUser
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryInvestor",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryInvestor
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryShareholderAccount",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryShareholderAccount
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryOrder",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryOrder
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryOrderAction",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryOrderAction
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryTrade",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryTrade
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryTradingAccount",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryTradingAccount
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPosition",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPosition
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryTradingFee",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryTradingFee
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryInvestorTradingFee",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryInvestorTradingFee
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryIPOQuota",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryIPOQuota
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryMarket",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryMarket
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryOrderFundDetail",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryOrderFundDetail
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryFundTransferDetail",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryFundTransferDetail
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPositionTransferDetail",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPositionTransferDetail
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPledgePosition",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPledgePosition
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPledgeInfo",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPledgeInfo
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryConversionBondInfo",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryConversionBondInfo
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryBondPutbackInfo",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryBondPutbackInfo
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryStandardBondPosition",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryStandardBondPosition
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQrySpecialMarketData",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQrySpecialMarketData
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPrematurityRepoOrder",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPrematurityRepoOrder
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryShareholderParam",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryShareholderParam
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryPeripheryPositionTransferDetail",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryPeripheryPositionTransferDetail
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryInvestorCondOrderLimitParam",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryInvestorCondOrderLimitParam
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryCondOrder",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryCondOrder
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryCondOrderAction",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryCondOrderAction
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryTradingNotice",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryTradingNotice
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryIPONumberResult",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryIPONumberResult
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    c.def("ReqQryIPOMatchNumberResult",
        autocxxpy::apply_function_transform<
            autocxxpy::function_constant<
                &CTORATstpTraderApi::ReqQryIPOMatchNumberResult
            >, 
            brigand::list<
            >
        >::value,
        pybind11::return_value_policy::reference,
        pybind11::call_guard<pybind11::gil_scoped_release>()
    );
    AUTOCXXPY_POST_REGISTER_CLASS(tag_vntora, CTORATstpTraderApi, c);
    module_vntora::objects.emplace("CTORATstpTraderApi", c);
}
