self.callbacks= {
 'OnDisconnected': {'reason': 'int'},
 'OnError': {'error_info': 'XTPRI'},
 'OnSubMarketData': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnUnSubMarketData': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnDepthMarketData': {'market_data': 'XTPMD', 'bid1_qty': 'int', 'bid1_count': 'int', 'max_bid1_count': 'int', 'ask1_qty': 'int', 'ask1_count': 'int', 'max_ask1_count': 'int'},
 'OnSubOrderBook': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnUnSubOrderBook': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnOrderBook': {'order_book': 'XTPOB'},
 'OnSubTickByTick': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnUnSubTickByTick': {'ticker': 'XTPST', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnTickByTick': {'tbt_data': 'XTPTBT'},
 'OnSubscribeAllMarketData': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllMarketData': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnSubscribeAllOrderBook': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllOrderBook': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnSubscribeAllTickByTick': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllTickByTick': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnQueryAllTickers': {'ticker_info': 'XTPQSI', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnQueryTickersPriceInfo': {'ticker_info': 'XTPTPI', 'error_info': 'XTPRI', 'is_last': 'bool'},
 'OnSubscribeAllOptionMarketData': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllOptionMarketData': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnSubscribeAllOptionOrderBook': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllOptionOrderBook': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnSubscribeAllOptionTickByTick': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'},
 'OnUnSubscribeAllOptionTickByTick': {'exchange_id': 'XTP_EXCHANGE_TYPE', 'error_info': 'XTPRI'}}


self.structs= {
 'XTPRI': {'error_id': 'int', 'error_msg': 'string'},
 'XTPRspInfoStruct': {'error_id': 'int', 'error_msg': 'string'},
 'XTPClientCrdExtendDebtInfo': {'xtp_id': 'int', 'debt_id': 'string'},
 'XTPClientQueryCrdDebtStockReq': {'market': 'enum', 'ticker': 'string'},
 'XTPClientQueryCrdPositionStkInfo': {'market': 'enum', 'ticker': 'string', 'limit_qty': 'int', 'yesterday_qty': 'int', 'left_qty': 'int', 'frozen_qty': 'int'},
 'XTPClientQueryCrdPositionStockReq': {'market': 'enum', 'ticker': 'string'},
 'XTPClientQueryCrdSurplusStkReqInfo': {'market': 'enum', 'ticker': 'string'},
 'XTPClientQueryCrdSurplusStkRspInfo': {'market': 'enum', 'ticker': 'string', 'transferable_quantity': 'int', 'transferred_quantity': 'int'},
 'XTPCrdCashRepayDebtInterestFeeRsp': {'xtp_id': 'int', 'request_amount': 'float', 'cash_repay_amount': 'float', 'debt_compact_id': 'string', 'unknow': 'string'},
 'XTPCrdCashRepayInfo': {'xtp_id': 'int', 'status': 'enum', 'request_amount': 'float', 'cash_repay_amount': 'float', 'position_effect': 'int', 'error_info': 'enum'},
 'XTPCrdCashRepayRsp': {'xtp_id': 'int', 'request_amount': 'float', 'cash_repay_amount': 'float'},
 'XTPCrdDebtInfo': {'debt_type': 'int', 'debt_id': 'string', 'position_id': 'int', 'order_xtp_id': 'int', 'debt_status': 'int', 'market': 'enum', 'ticker': 'string', 'order_date': 'int', 'end_date': 'int', 'orig_end_date': 'int', 'is_extended': 'bool', 'remain_amt': 'float', 'remain_qty': 'int', 'remain_principal': 'float', 'due_right_qty': 'int', 'unknown': 'int'},
 'XTPCrdDebtStockInfo': {'market': 'enum', 'ticker': 'string', 'remain_quantity': 'int', 'order_withhold_quantity': 'int'},
 'XTPCrdFundInfo': {'maintenance_ratio': 'float', 'all_asset': 'float', 'all_debt': 'float', 'line_of_credit': 'float', 'guaranty': 'float', 'position_amount': 'float'},
 'XTPFundTransferNotice': {'serial_id': 'int', 'transfer_type': 'enum', 'amount': 'float', 'oper_status': 'enum', 'transfer_time': 'int'},
 'XTPOrderCancelInfo': {'order_cancel_xtp_id': 'int', 'order_xtp_id': 'int'},
 'XTPOrderInfo': {'order_xtp_id': 'int', 'order_client_id': 'int', 'order_cancel_client_id': 'int', 'order_cancel_xtp_id': 'int', 'ticker': 'string', 'market': 'enum', 'price': 'float', 'quantity': 'int', 'price_type': 'enum', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'qty_traded': 'int', 'qty_left': 'int', 'insert_time': 'int', 'update_time': 'int', 'cancel_time': 'int', 'trade_amount': 'float', 'order_local_id': 'string', 'order_status': 'enum', 'order_submit_status': 'enum', 'order_type': 'string'},
 'XTPOrderInsertInfo': {'order_xtp_id': 'int', 'order_client_id': 'int', 'ticker': 'string', 'market': 'enum', 'price': 'float', 'stop_price': 'float', 'quantity': 'int', 'price_type': 'enum', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum'},
 'XTPQueryAssetRsp': {'total_asset': 'float', 'buying_power': 'float', 'security_asset': 'float', 'fund_buy_amount': 'float', 'fund_buy_fee': 'float', 'fund_sell_amount': 'float', 'fund_sell_fee': 'float', 'withholding_amount': 'float', 'account_type': 'enum', 'frozen_margin': 'float', 'frozen_exec_cash': 'float', 'frozen_exec_fee': 'float', 'pay_later': 'float', 'preadva_pay': 'float', 'orig_banlance': 'float', 'banlance': 'float', 'deposit_withdraw': 'float', 'trade_netting': 'float', 'captial_asset': 'float', 'force_freeze_amount': 'float', 'preferred_amount': 'float', 'repay_stock_aval_banlance': 'float', 'unknown': 'int'},
 'XTPQueryETFBaseReq': {'market': 'enum', 'ticker': 'string'},
 'XTPQueryETFBaseRsp': {'market': 'enum', 'etf': 'string', 'subscribe_redemption_ticker': 'string', 'unit': 'int', 'subscribe_status': 'int', 'redemption_status': 'int', 'max_cash_ratio': 'float', 'estimate_amount': 'float', 'cash_component': 'float', 'net_value': 'float', 'total_amount': 'float'},
 'XTPQueryETFComponentReq': {'market': 'enum', 'ticker': 'string'},
 'XTPQueryETFComponentRsp': {'market': 'enum', 'ticker': 'string', 'component_ticker': 'string', 'component_name': 'string', 'quantity': 'int', 'component_market': 'enum', 'replace_type': 'enum', 'premium_ratio': 'float', 'amount': 'float'},
 'XTPQueryFundTransferLogReq': {'serial_id': 'int'},
 'XTPQueryIPOQuotaRsp': {'market': 'enum', 'quantity': 'int'},
 'XTPQueryIPOTickerRsp': {'market': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'price': 'float', 'unit': 'int', 'qty_upper_limit': 'int'},
 'XTPQueryOptionAuctionInfoReq': {'market': 'enum', 'ticker': 'string'},
 'XTPQueryOptionAuctionInfoRsp': {'ticker': 'string', 'security_id_source': 'enum', 'symbol': 'string', 'contract_id': 'string', 'underlying_security_id': 'string', 'underlying_security_id_source': 'enum', 'list_date': 'int', 'last_trade_date': 'int', 'ticker_type': 'enum', 'day_trading': 'int', 'call_or_put': 'enum', 'delivery_day': 'int', 'delivery_month': 'int', 'exercise_type': 'enum', 'exercise_begin_date': 'int', 'exercise_end_date': 'int', 'exercise_price': 'float', 'qty_unit': 'int', 'contract_unit': 'int', 'contract_position': 'int', 'prev_close_price': 'float', 'prev_clearing_price': 'float', 'lmt_buy_max_qty': 'int', 'lmt_buy_min_qty': 'int', 'lmt_sell_max_qty': 'int', 'lmt_sell_min_qty': 'int', 'mkt_buy_max_qty': 'int', 'mkt_buy_min_qty': 'int', 'mkt_sell_max_qty': 'int', 'mkt_sell_min_qty': 'int', 'price_tick': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'sell_margin': 'float', 'margin_ratio_param1': 'float', 'margin_ratio_param2': 'float', 'unknown': 'int'},
 'XTPQueryOrderReq': {'ticker': 'string', 'begin_time': 'int', 'end_time': 'int'},
 'XTPQueryReportByExecIdReq': {'order_xtp_id': 'int', 'exec_id': 'string'},
 'XTPQueryStkPositionRsp': {'ticker': 'string', 'ticker_name': 'string', 'market': 'enum', 'total_qty': 'int', 'sellable_qty': 'int', 'avg_price': 'float', 'unrealized_pnl': 'float', 'yesterday_position': 'int', 'purchase_redeemable_qty': 'int', 'position_direction': 'enum', 'reserved1': 'int', 'executable_option': 'int', 'lockable_position': 'int', 'executable_underlying': 'int', 'locked_position': 'int', 'usable_locked_position': 'int', 'unknown': 'int'},
 'XTPQueryStructuredFundInfoReq': {'exchange_id': 'enum', 'sf_ticker': 'string'},
 'XTPQueryTraderReq': {'ticker': 'string', 'begin_time': 'int', 'end_time': 'int'},
 'XTPStructuredFundInfo': {'exchange_id': 'enum', 'sf_ticker': 'string', 'sf_ticker_name': 'string', 'ticker': 'string', 'ticker_name': 'string', 'split_merge_status': 'enum', 'ratio': 'int', 'min_split_qty': 'int', 'min_merge_qty': 'int', 'net_price': 'float'},
 'XTPTradeReport': {'order_xtp_id': 'int', 'order_client_id': 'int', 'ticker': 'string', 'market': 'enum', 'local_order_id': 'int', 'exec_id': 'string', 'price': 'float', 'quantity': 'int', 'trade_time': 'int', 'trade_amount': 'float', 'report_index': 'int', 'order_exch_id': 'string', 'trade_type': 'string', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'branch_pbu': 'string'},
 'OrderBookStruct': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'qty': 'int', 'turnover': 'float', 'trades_count': 'int', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'data_time': 'int'},
 'XTPMD': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'pre_close_price': 'float', 'open_price': 'float', 'high_price': 'float', 'low_price': 'float', 'close_price': 'float', 'pre_total_long_positon': 'int', 'total_long_positon': 'int', 'pre_settl_price': 'float', 'settl_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'pre_delta': 'float', 'curr_delta': 'float', 'data_time': 'int', 'qty': 'int', 'turnover': 'float', 'avg_price': 'float', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'trades_count': 'int', 'ticker_status': 'string', 'data_type': 'enum', 'r4': 'int'},
 'XTPMarketDataOptionExData': {'auction_price': 'float', 'auction_qty': 'int', 'last_enquiry_time': 'int'},
 'XTPMarketDataStockExData': {'total_bid_qty': 'int', 'total_ask_qty': 'int', 'ma_bid_price': 'float', 'ma_ask_price': 'float', 'ma_bond_bid_price': 'float', 'ma_bond_ask_price': 'float', 'yield_to_maturity': 'float', 'iopv': 'float', 'etf_buy_count': 'int', 'etf_sell_count': 'int', 'etf_buy_qty': 'float', 'etf_buy_money': 'float', 'etf_sell_qty': 'float', 'etf_sell_money': 'float', 'total_warrant_exec_qty': 'float', 'warrant_lower_price': 'float', 'warrant_upper_price': 'float', 'cancel_buy_count': 'int', 'cancel_sell_count': 'int', 'cancel_buy_qty': 'float', 'cancel_sell_qty': 'float', 'cancel_buy_money': 'float', 'cancel_sell_money': 'float', 'total_buy_count': 'int', 'total_sell_count': 'int', 'duration_after_buy': 'int', 'duration_after_sell': 'int', 'num_bid_orders': 'int', 'num_ask_orders': 'int', 'pre_iopv': 'float', 'r1': 'int', 'r2': 'int'},
 'XTPMarketDataStruct': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'pre_close_price': 'float', 'open_price': 'float', 'high_price': 'float', 'low_price': 'float', 'close_price': 'float', 'pre_total_long_positon': 'int', 'total_long_positon': 'int', 'pre_settl_price': 'float', 'settl_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'pre_delta': 'float', 'curr_delta': 'float', 'data_time': 'int', 'qty': 'int', 'turnover': 'float', 'avg_price': 'float', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'trades_count': 'int', 'ticker_status': 'string', 'data_type': 'enum', 'r4': 'int'},
 'XTPOB': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'qty': 'int', 'turnover': 'float', 'trades_count': 'int', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'data_time': 'int'},
 'XTPQSI': {'exchange_id': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'ticker_type': 'enum', 'pre_close_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'price_tick': 'float', 'buy_qty_unit': 'int', 'sell_qty_unit': 'int'},
 'XTPQuoteStaticInfo': {'exchange_id': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'ticker_type': 'enum', 'pre_close_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'price_tick': 'float', 'buy_qty_unit': 'int', 'sell_qty_unit': 'int'},
 'XTPST': {'exchange_id': 'enum', 'ticker': 'string'},
 'XTPSpecificTickerStruct': {'exchange_id': 'enum', 'ticker': 'string'},
 'XTPTBT': {'exchange_id': 'enum', 'ticker': 'string', 'seq': 'int', 'data_time': 'int', 'type': 'enum'},
 'XTPTPI': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float'},
 'XTPTickByTickEntrust': {'channel_no': 'int', 'seq': 'int', 'price': 'float', 'qty': 'int', 'side': 'string', 'ord_type': 'string'},
 'XTPTickByTickStruct': {'exchange_id': 'enum', 'ticker': 'string', 'seq': 'int', 'data_time': 'int', 'type': 'enum'},
 'XTPTickByTickTrade': {'channel_no': 'int', 'seq': 'int', 'price': 'float', 'qty': 'int', 'money': 'float', 'bid_no': 'int', 'ask_no': 'int', 'trade_flag': 'string'},
 'XTPTickerPriceInfo': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float'},
 'XTP_MARKETDATA_TYPE': {}
 }

self.functions 
{
 'QueryAllTickers': {'exchange_id': 'XTP_EXCHANGE_TYPE'},
 'QueryTickersPriceInfo': {'ticker': 'char', 'count': 'int', 'exchange_id': 'XTP_EXCHANGE_TYPE'},
 'QueryAllTickersPriceInfo': {}
}


self.lines={
 'OnDisconnected': 'virtual void OnDisconnected(int reason) ',
 'OnError': 'virtual void OnError(XTPRI *error_info) ',
 'OnSubMarketData': 'virtual void OnSubMarketData(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnUnSubMarketData': 'virtual void OnUnSubMarketData(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnDepthMarketData': 'virtual void OnDepthMarketData(XTPMD *market_data, int64_t bid1_qty[], int32_t bid1_count, int32_t max_bid1_count, int64_t ask1_qty[], int32_t ask1_count, int32_t max_ask1_count) ',
 'OnSubOrderBook': 'virtual void OnSubOrderBook(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnUnSubOrderBook': 'virtual void OnUnSubOrderBook(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnOrderBook': 'virtual void OnOrderBook(XTPOB *order_book) ',
 'OnSubTickByTick': 'virtual void OnSubTickByTick(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnUnSubTickByTick': 'virtual void OnUnSubTickByTick(XTPST *ticker, XTPRI *error_info, bool is_last) ',
 'OnTickByTick': 'virtual void OnTickByTick(XTPTBT *tbt_data) ',
 'OnSubscribeAllMarketData': 'virtual void OnSubscribeAllMarketData(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllMarketData': 'virtual void OnUnSubscribeAllMarketData(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnSubscribeAllOrderBook': 'virtual void OnSubscribeAllOrderBook(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllOrderBook': 'virtual void OnUnSubscribeAllOrderBook(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnSubscribeAllTickByTick': 'virtual void OnSubscribeAllTickByTick(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllTickByTick': 'virtual void OnUnSubscribeAllTickByTick(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnQueryAllTickers': 'virtual void OnQueryAllTickers(XTPQSI* ticker_info, XTPRI *error_info, bool is_last) ',
 'OnQueryTickersPriceInfo': 'virtual void OnQueryTickersPriceInfo(XTPTPI* ticker_info, XTPRI *error_info, bool is_last) ',
 'OnSubscribeAllOptionMarketData': 'virtual void OnSubscribeAllOptionMarketData(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllOptionMarketData': 'virtual void OnUnSubscribeAllOptionMarketData(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnSubscribeAllOptionOrderBook': 'virtual void OnSubscribeAllOptionOrderBook(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllOptionOrderBook': 'virtual void OnUnSubscribeAllOptionOrderBook(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnSubscribeAllOptionTickByTick': 'virtual void OnSubscribeAllOptionTickByTick(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) ',
 'OnUnSubscribeAllOptionTickByTick': 'virtual void OnUnSubscribeAllOptionTickByTick(XTP_EXCHANGE_TYPE exchange_id, XTPRI *error_info) '
}