self.callbacks= {
    'OnDisconnected': {'session_id': 'int', 'reason': 'int'},
    'OnError': {'error_info': 'XTPRI'},
    'OnOrderEvent': {'order_info': 'XTPOrderInfo', 'error_info': 'XTPRI', 'session_id': 'int'},
    'OnTradeEvent': {'trade_info': 'XTPTradeReport', 'session_id': 'int'},
    'OnCancelOrderError': {'cancel_info': 'XTPOrderCancelInfo', 'error_info': 'XTPRI', 'session_id': 'int'},
    'OnQueryOrder': {'order_info': 'XTPQueryOrderRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryTrade': {'trade_info': 'XTPQueryTradeRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryPosition': {'position': 'XTPQueryStkPositionRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryAsset': {'asset': 'XTPQueryAssetRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryStructuredFund': {'fund_info': 'XTPStructuredFundInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryFundTransfer': {'fund_transfer_info': 'XTPFundTransferNotice', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnFundTransfer': {'fund_transfer_info': 'XTPFundTransferNotice', 'error_info': 'XTPRI', 'session_id': 'int'},
    'OnQueryETF': {'etf_info': 'XTPQueryETFBaseRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryETFBasket': {'etf_component_info': 'XTPQueryETFComponentRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryIPOInfoList': {'ipo_info': 'XTPQueryIPOTickerRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryIPOQuotaInfo': {'quota_info': 'XTPQueryIPOQuotaRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryOptionAuctionInfo': {'option_info': 'XTPQueryOptionAuctionInfoRsp', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnCreditCashRepay': {'cash_repay_info': 'XTPCrdCashRepayRsp', 'error_info': 'XTPRI', 'session_id': 'int'},
    'OnQueryCreditCashRepayInfo': {'cash_repay_info': 'XTPCrdCashRepayInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryCreditFundInfo': {'fund_info': 'XTPCrdFundInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'session_id': 'int'},
    'OnQueryCreditDebtInfo': {'debt_info': 'XTPCrdDebtInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryCreditTickerDebtInfo': {'debt_info': 'XTPCrdDebtStockInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryCreditAssetDebtInfo': {'remain_amount': 'double', 'error_info': 'XTPRI', 'request_id': 'int', 'session_id': 'int'},
    'OnQueryCreditTickerAssignInfo': {'assign_info': 'XTPClientQueryCrdPositionStkInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'is_last': 'bool', 'session_id': 'int'},
    'OnQueryCreditExcessStock': {'stock_info': 'XTPClientQueryCrdSurplusStkRspInfo', 'error_info': 'XTPRI', 'request_id': 'int', 'session_id': 'int'}}
self.structs ={
    'XTPRI': {'error_id': 'int', 'error_msg': 'string'},
    'XTPRspInfoStruct': {'error_id': 'int', 'error_msg': 'string'},
    'XTPClientCrdExtendDebtInfo': {'xtp_id': 'int', 'debt_id': 'string'},
    'XTPClientQueryCrdDebtStockReq': {'market': 'enum', 'ticker': 'string'}
   , 'XTPClientQueryCrdPositionStkInfo': {'market': 'enum', 'ticker': 'string', 'limit_qty': 'int', 'yesterday_qty': 'int', 'left_qty': 'int', 'frozen_qty': 'int'},
    'XTPClientQueryCrdPositionStockReq': {'market': 'enum', 'ticker': 'string'},
    'XTPClientQueryCrdSurplusStkReqInfo': {'market': 'enum', 'ticker': 'string'},
    'XTPClientQueryCrdSurplusStkRspInfo': {'market': 'enum', 'ticker': 'string', 'transferable_quantity': 'int', 'transferred_quantity': 'int'},
    'XTPCrdCashRepayDebtInterestFeeRsp': {'xtp_id': 'int', 'request_amount': 'float', 'cash_repay_amount': 'float', 'debt_compact_id': 'string', 'unknow': 'string'},
    'XTPCrdCashRepayInfo': {'xtp_id': 'int', 'status': 'enum', 'request_amount': 'float', 'cash_repay_amount': 'float', 'position_effect': 'int', 'error_info': 'enum'},
    'XTPCrdCashRepayRsp': {'xtp_id': 'int', 'request_amount': 'float', 'cash_repay_amount': 'float'},
    'XTPCrdDebtInfo': {'debt_type': 'int', 'debt_id': 'string', 'position_id': 'int', 'order_xtp_id': 'int', 'debt_status': 'int', 'market': 'enum', 'ticker': 'string', 'order_date': 'int', 'end_date': 'int', 'orig_end_date': 'int', 'is_extended': 'bool', 'remain_amt': 'float', 'remain_qty': 'int', 'remain_principal': 'float', 'due_right_qty': 'int', 'unknown': 'int'},
    'XTPCrdDebtStockInfo': {'market': 'enum', 'ticker': 'string', 'remain_quantity': 'int', 'order_withhold_quantity': 'int'},
    'XTPCrdFundInfo': {'maintenance_ratio': 'float', 'all_asset': 'float', 'all_debt': 'float', 'line_of_credit': 'float', 'guaranty': 'float', 'position_amount': 'float'},
    'XTPFundTransferLog': {'serial_id': 'int', 'transfer_type': 'enum', 'amount': 'float', 'oper_status': 'enum', 'transfer_time': 'int'},
    'XTPFundTransferNotice': {'serial_id': 'int', 'transfer_type': 'enum', 'amount': 'float', 'oper_status': 'enum', 'transfer_time': 'int'},
    'XTPOrderCancelInfo': {'order_cancel_xtp_id': 'int', 'order_xtp_id': 'int'},
    'XTPOrderInfo': {'order_xtp_id': 'int', 'order_client_id': 'int', 'order_cancel_client_id': 'int', 'order_cancel_xtp_id': 'int', 'ticker': 'string', 'market': 'enum', 'price': 'float', 'quantity': 'int', 'price_type': 'enum', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'qty_traded': 'int', 'qty_left': 'int', 'insert_time': 'int', 'update_time': 'int', 'cancel_time': 'int', 'trade_amount': 'float', 'order_local_id': 'string', 'order_status': 'enum', 'order_submit_status': 'enum', 'order_type': 'string'},
    'XTPOrderInsertInfo': {'order_xtp_id': 'int', 'order_client_id': 'int', 'ticker': 'string', 'market': 'enum', 'price': 'float', 'stop_price': 'float', 'quantity': 'int', 'price_type': 'enum', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum'},
    'XTPQueryAssetRsp': {'total_asset': 'float', 'buying_power': 'float', 'security_asset': 'float', 'fund_buy_amount': 'float', 'fund_buy_fee': 'float', 'fund_sell_amount': 'float', 'fund_sell_fee': 'float', 'withholding_amount': 'float', 'account_type': 'enum', 'frozen_margin': 'float', 'frozen_exec_cash': 'float', 'frozen_exec_fee': 'float', 'pay_later': 'float', 'preadva_pay': 'float', 'orig_banlance': 'float', 'banlance': 'float', 'deposit_withdraw': 'float', 'trade_netting': 'float', 'captial_asset': 'float', 'force_freeze_amount': 'float', 'preferred_amount': 'float', 'repay_stock_aval_banlance': 'float', 'unknown': 'int'},
    'XTPQueryETFBaseReq': {'market': 'enum', 'ticker': 'string'},
    'XTPQueryETFBaseRsp': {'market': 'enum', 'etf': 'string', 'subscribe_redemption_ticker': 'string', 'unit': 'int', 'subscribe_status': 'int', 'redemption_status': 'int', 'max_cash_ratio': 'float', 'estimate_amount': 'float', 'cash_component': 'float', 'net_value': 'float', 'total_amount': 'float'},
    'XTPQueryETFComponentReq': {'market': 'enum', 'ticker': 'string'},
    'XTPQueryETFComponentRsp': {'market': 'enum', 'ticker': 'string', 'component_ticker': 'string', 'component_name': 'string', 'quantity': 'int', 'component_market': 'enum', 'replace_type': 'enum', 'premium_ratio': 'float', 'amount': 'float'},
    'XTPQueryFundTransferLogReq': {'serial_id': 'int'},
    'XTPQueryIPOQuotaRsp': {'market': 'enum', 'quantity': 'int'},
    'XTPQueryIPOTickerRsp': {'market': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'price': 'float', 'unit': 'int', 'qty_upper_limit': 'int'},
    'XTPQueryOptionAuctionInfoReq': {'market': 'enum', 'ticker': 'string'},
    'XTPQueryOptionAuctionInfoRsp': {'ticker': 'string', 'security_id_source': 'enum', 'symbol': 'string', 'contract_id': 'string', 'underlying_security_id': 'string', 'underlying_security_id_source': 'enum', 'list_date': 'int', 'last_trade_date': 'int', 'ticker_type': 'enum', 'day_trading': 'int', 'call_or_put': 'enum', 'delivery_day': 'int', 'delivery_month': 'int', 'exercise_type': 'enum', 'exercise_begin_date': 'int', 'exercise_end_date': 'int', 'exercise_price': 'float', 'qty_unit': 'int', 'contract_unit': 'int', 'contract_position': 'int', 'prev_close_price': 'float', 'prev_clearing_price': 'float', 'lmt_buy_max_qty': 'int', 'lmt_buy_min_qty': 'int', 'lmt_sell_max_qty': 'int', 'lmt_sell_min_qty': 'int', 'mkt_buy_max_qty': 'int', 'mkt_buy_min_qty': 'int', 'mkt_sell_max_qty': 'int', 'mkt_sell_min_qty': 'int', 'price_tick': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'sell_margin': 'float', 'margin_ratio_param1': 'float', 'margin_ratio_param2': 'float', 'unknown': 'int'},
    'XTPQueryOrderReq': {'ticker': 'string', 'begin_time': 'int', 'end_time': 'int'},
    'XTPQueryOrderRsp': {'order_xtp_id': 'int', 'order_client_id': 'int', 'order_cancel_client_id': 'int', 'order_cancel_xtp_id': 'int', 'ticker': 'string', 'market': 'enum', 'price': 'float', 'quantity': 'int', 'price_type': 'enum', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'qty_traded': 'int', 'qty_left': 'int', 'insert_time': 'int', 'update_time': 'int', 'cancel_time': 'int', 'trade_amount': 'float', 'order_local_id': 'string', 'order_status': 'enum', 'order_submit_status': 'enum', 'order_type': 'string'},
    'XTPQueryReportByExecIdReq': {'order_xtp_id': 'int', 'exec_id': 'string'},
    'XTPQueryStkPositionRsp': {'ticker': 'string', 'ticker_name': 'string', 'market': 'enum', 'total_qty': 'int', 'sellable_qty': 'int', 'avg_price': 'float', 'unrealized_pnl': 'float', 'yesterday_position': 'int', 'purchase_redeemable_qty': 'int', 'position_direction': 'enum', 'reserved1': 'int', 'executable_option': 'int', 'lockable_position': 'int', 'executable_underlying': 'int', 'locked_position': 'int', 'usable_locked_position': 'int', 'unknown': 'int'},
    'XTPQueryStructuredFundInfoReq': {'exchange_id': 'enum', 'sf_ticker': 'string'},
    'XTPQueryTradeRsp': {'order_xtp_id': 'int', 'order_client_id': 'int', 'ticker': 'string', 'market': 'enum', 'local_order_id': 'int', 'exec_id': 'string', 'price': 'float', 'quantity': 'int', 'trade_time': 'int', 'trade_amount': 'float', 'report_index': 'int', 'order_exch_id': 'string', 'trade_type': 'string', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'branch_pbu': 'string'},
    'XTPQueryTraderReq': {'ticker': 'string', 'begin_time': 'int', 'end_time': 'int'},
    'XTPStructuredFundInfo': {'exchange_id': 'enum', 'sf_ticker': 'string', 'sf_ticker_name': 'string', 'ticker': 'string', 'ticker_name': 'string', 'split_merge_status': 'enum', 'ratio': 'int', 'min_split_qty': 'int', 'min_merge_qty': 'int', 'net_price': 'float'},
    'XTPTradeReport': {'order_xtp_id': 'int', 'order_client_id': 'int', 'ticker': 'string', 'market': 'enum', 'local_order_id': 'int', 'exec_id': 'string', 'price': 'float', 'quantity': 'int', 'trade_time': 'int', 'trade_amount': 'float', 'report_index': 'int', 'order_exch_id': 'string', 'trade_type': 'string', 'side': 'int', 'position_effect': 'int', 'business_type': 'enum', 'branch_pbu': 'string'},
    'OrderBookStruct': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'qty': 'int', 'turnover': 'float', 'trades_count': 'int', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'data_time': 'int'},
    'XTPMD': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'pre_close_price': 'float', 'open_price': 'float', 'high_price': 'float', 'low_price': 'float', 'close_price': 'float', 'pre_total_long_positon': 'int', 'total_long_positon': 'int', 'pre_settl_price': 'float', 'settl_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'pre_delta': 'float', 'curr_delta': 'float', 'data_time': 'int', 'qty': 'int', 'turnover': 'float', 'avg_price': 'float', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'trades_count': 'int', 'ticker_status': 'string', 'data_type': 'enum', 'r4': 'int'},
    'XTPMarketDataOptionExData': {'auction_price': 'float', 'auction_qty': 'int', 'last_enquiry_time': 'int'},
    'XTPMarketDataStockExData': {'total_bid_qty': 'int', 'total_ask_qty': 'int', 'ma_bid_price': 'float', 'ma_ask_price': 'float', 'ma_bond_bid_price': 'float', 'ma_bond_ask_price': 'float', 'yield_to_maturity': 'float', 'iopv': 'float', 'etf_buy_count': 'int', 'etf_sell_count': 'int', 'etf_buy_qty': 'float', 'etf_buy_money': 'float', 'etf_sell_qty': 'float', 'etf_sell_money': 'float', 'total_warrant_exec_qty': 'float', 'warrant_lower_price': 'float', 'warrant_upper_price': 'float', 'cancel_buy_count': 'int', 'cancel_sell_count': 'int', 'cancel_buy_qty': 'float', 'cancel_sell_qty': 'float', 'cancel_buy_money': 'float', 'cancel_sell_money': 'float', 'total_buy_count': 'int', 'total_sell_count': 'int', 'duration_after_buy': 'int', 'duration_after_sell': 'int', 'num_bid_orders': 'int', 'num_ask_orders': 'int', 'pre_iopv': 'float', 'r1': 'int', 'r2': 'int'},
    'XTPMarketDataStruct': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'pre_close_price': 'float', 'open_price': 'float', 'high_price': 'float', 'low_price': 'float', 'close_price': 'float', 'pre_total_long_positon': 'int', 'total_long_positon': 'int', 'pre_settl_price': 'float', 'settl_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'pre_delta': 'float', 'curr_delta': 'float', 'data_time': 'int', 'qty': 'int', 'turnover': 'float', 'avg_price': 'float', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'trades_count': 'int', 'ticker_status': 'string', 'data_type': 'enum', 'r4': 'int'},
    'XTPOB': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float', 'qty': 'int', 'turnover': 'float', 'trades_count': 'int', 'bid': 'float', 'ask': 'float', 'bid_qty': 'int', 'ask_qty': 'int', 'data_time': 'int'},
    'XTPQSI': {'exchange_id': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'ticker_type': 'enum', 'pre_close_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'price_tick': 'float', 'buy_qty_unit': 'int', 'sell_qty_unit': 'int'},
    'XTPQuoteStaticInfo': {'exchange_id': 'enum', 'ticker': 'string', 'ticker_name': 'string', 'ticker_type': 'enum', 'pre_close_price': 'float', 'upper_limit_price': 'float', 'lower_limit_price': 'float', 'price_tick': 'float', 'buy_qty_unit': 'int', 'sell_qty_unit': 'int'},
    'XTPST': {'exchange_id': 'enum', 'ticker': 'string'},
    'XTPSpecificTickerStruct': {'exchange_id': 'enum', 'ticker': 'string'}
   , 'XTPTBT': {'exchange_id': 'enum', 'ticker': 'string', 'seq': 'int', 'data_time': 'int', 'type': 'enum'},
    'XTPTickByTickEntrust': {'channel_no': 'int', 'seq': 'int', 'price': 'float', 'qty': 'int', 'side': 'string', 'ord_type': 'string'},
    'XTPTickByTickStruct': {'exchange_id': 'enum', 'ticker': 'string', 'seq': 'int', 'data_time': 'int', 'type': 'enum'},
    'XTPTickByTickTrade': {'channel_no': 'int', 'seq': 'int', 'price': 'float', 'qty': 'int', 'money': 'float', 'bid_no': 'int', 'ask_no': 'int', 'trade_flag': 'string'},
    'XTPTickerPriceInfo': {'exchange_id': 'enum', 'ticker': 'string', 'last_price': 'float'},
    'XTP_MARKETDATA_TYPE': {}
}


self.functions ={
 'QueryOrderByXTPID': {'order_xtp_id': 'int', 'session_id': 'int', 'request_id': 'int'},
 'QueryOrders': {'query_param': 'XTPQueryOrderReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryTradesByXTPID': {'order_xtp_id': 'int', 'session_id': 'int', 'request_id': 'int'},
 'QueryTrades': {'query_param': 'XTPQueryTraderReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryPosition': {'ticker': 'char', 'session_id': 'int', 'request_id': 'int'},
 'QueryAsset': {'session_id': 'int', 'request_id': 'int'},
 'QueryStructuredFund': {'query_param': 'XTPQueryStructuredFundInfoReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryFundTransfer': {'query_param': 'XTPQueryFundTransferLogReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryETF': {'query_param': 'XTPQueryETFBaseReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryETFTickerBasket': {'query_param': 'XTPQueryETFComponentReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryIPOInfoList': {'session_id': 'int', 'request_id': 'int'},
 'QueryIPOQuotaInfo': {'session_id': 'int', 'request_id': 'int'},
 'QueryOptionAuctionInfo': {'query_param': 'XTPQueryOptionAuctionInfoReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryCreditCashRepayInfo': {'session_id': 'int', 'request_id': 'int'},
 'QueryCreditFundInfo': {'session_id': 'int', 'request_id': 'int'},
 'QueryCreditDebtInfo': {'session_id': 'int', 'request_id': 'int'},
 'QueryCreditTickerDebtInfo': {'query_param': 'XTPClientQueryCrdDebtStockReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryCreditAssetDebtInfo': {'session_id': 'int', 'request_id': 'int'},
 'QueryCreditTickerAssignInfo': {'query_param': 'XTPClientQueryCrdPositionStockReq', 'session_id': 'int', 'request_id': 'int'},
 'QueryCreditExcessStock': {'query_param': 'XTPClientQueryCrdSurplusStkReqInfo', 'session_id': 'int', 'request_id': 'int'}}
