#include <iostream>
#include <string>
#include <string_view>
#include <pybind11/pybind11.h>

#include "dispatcher.h"
#include "property_helper.h"
#include "wrapper_helper.h"
#include "class_generators.h"
#include "wrappers.h"

#include "ctp/ThostFtdcTraderApi.h"


void generate_class_CThostFtdcQryBrokerUserFunctionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryBrokerUserFunctionField>(m, "CThostFtdcQryBrokerUserFunctionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryBrokerUserFunctionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryBrokerUserFunctionField, UserID)
    ;
}
void generate_class_CThostFtdcQryTraderOfferField(pybind11::module &m)
{
    py::class_<CThostFtdcQryTraderOfferField>(m, "CThostFtdcQryTraderOfferField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryTraderOfferField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryTraderOfferField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryTraderOfferField, TraderID)
    ;
}
void generate_class_CThostFtdcQrySyncDepositField(pybind11::module &m)
{
    py::class_<CThostFtdcQrySyncDepositField>(m, "CThostFtdcQrySyncDepositField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQrySyncDepositField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQrySyncDepositField, DepositSeqNo)
    ;
}
void generate_class_CThostFtdcQrySettlementInfoField(pybind11::module &m)
{
    py::class_<CThostFtdcQrySettlementInfoField>(m, "CThostFtdcQrySettlementInfoField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQrySettlementInfoField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQrySettlementInfoField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQrySettlementInfoField, TradingDay)
    ;
}
void generate_class_CThostFtdcQryExchangeMarginRateField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeMarginRateField>(m, "CThostFtdcQryExchangeMarginRateField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateField, HedgeFlag)
    ;
}
void generate_class_CThostFtdcQryExchangeMarginRateAdjustField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeMarginRateAdjustField>(m, "CThostFtdcQryExchangeMarginRateAdjustField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateAdjustField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateAdjustField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryExchangeMarginRateAdjustField, HedgeFlag)
    ;
}
void generate_class_CThostFtdcQryExchangeRateField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeRateField>(m, "CThostFtdcQryExchangeRateField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeRateField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryExchangeRateField, FromCurrencyID)
        .DEF_PROPERTY(CThostFtdcQryExchangeRateField, ToCurrencyID)
    ;
}
void generate_class_CThostFtdcQrySyncFundMortgageField(pybind11::module &m)
{
    py::class_<CThostFtdcQrySyncFundMortgageField>(m, "CThostFtdcQrySyncFundMortgageField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQrySyncFundMortgageField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQrySyncFundMortgageField, MortgageSeqNo)
    ;
}
void generate_class_CThostFtdcQryHisOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcQryHisOrderField>(m, "CThostFtdcQryHisOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, OrderSysID)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, InsertTimeStart)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, InsertTimeEnd)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, TradingDay)
        .DEF_PROPERTY(CThostFtdcQryHisOrderField, SettlementID)
    ;
}
void generate_class_CThostFtdcOptionInstrMiniMarginField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrMiniMarginField>(m, "CThostFtdcOptionInstrMiniMarginField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, MinMargin)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, ValueMethod)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, IsRelative)
        .DEF_PROPERTY(CThostFtdcOptionInstrMiniMarginField, ExchangeID)
    ;
}
void generate_class_CThostFtdcOptionInstrMarginAdjustField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrMarginAdjustField>(m, "CThostFtdcOptionInstrMarginAdjustField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, SShortMarginRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, SShortMarginRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, HShortMarginRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, HShortMarginRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, AShortMarginRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, AShortMarginRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, IsRelative)
        .DEF_PROPERTY(CThostFtdcOptionInstrMarginAdjustField, ExchangeID)
    ;
}
void generate_class_CThostFtdcOptionInstrCommRateField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrCommRateField>(m, "CThostFtdcOptionInstrCommRateField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, OpenRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, OpenRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, CloseRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, CloseRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, CloseTodayRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, CloseTodayRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, StrikeRatioByMoney)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, StrikeRatioByVolume)
        .DEF_PROPERTY(CThostFtdcOptionInstrCommRateField, ExchangeID)
    ;
}
void generate_class_CThostFtdcOptionInstrTradeCostField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrTradeCostField>(m, "CThostFtdcOptionInstrTradeCostField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, FixedMargin)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, MiniMargin)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, Royalty)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, ExchFixedMargin)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, ExchMiniMargin)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradeCostField, ExchangeID)
    ;
}
void generate_class_CThostFtdcQryOptionInstrTradeCostField(pybind11::module &m)
{
    py::class_<CThostFtdcQryOptionInstrTradeCostField>(m, "CThostFtdcQryOptionInstrTradeCostField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, InputPrice)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, UnderlyingPrice)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradeCostField, ExchangeID)
    ;
}
void generate_class_CThostFtdcQryOptionInstrCommRateField(pybind11::module &m)
{
    py::class_<CThostFtdcQryOptionInstrCommRateField>(m, "CThostFtdcQryOptionInstrCommRateField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryOptionInstrCommRateField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrCommRateField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrCommRateField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrCommRateField, ExchangeID)
    ;
}
void generate_class_CThostFtdcIndexPriceField(pybind11::module &m)
{
    py::class_<CThostFtdcIndexPriceField>(m, "CThostFtdcIndexPriceField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcIndexPriceField, BrokerID)
        .DEF_PROPERTY(CThostFtdcIndexPriceField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcIndexPriceField, ClosePrice)
        .DEF_PROPERTY(CThostFtdcIndexPriceField, ExchangeID)
    ;
}
void generate_class_CThostFtdcInputExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcInputExecOrderField>(m, "CThostFtdcInputExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, InvestorID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, UserID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, Volume)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, RequestID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, OffsetFlag)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, ActionType)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, PosiDirection)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, ReservePositionFlag)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, CloseFlag)
        .DEF_PROPERTY(CThostFtdcInputExecOrderField, ExchangeID)
    ;
}
void generate_class_CThostFtdcInputExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcInputExecOrderActionField>(m, "CThostFtdcInputExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, ExecOrderActionRef)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, RequestID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, FrontID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, SessionID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, UserID)
        .DEF_PROPERTY(CThostFtdcInputExecOrderActionField, InstrumentID)
    ;
}
void generate_class_CThostFtdcExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcExecOrderField>(m, "CThostFtdcExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExecOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, InvestorID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcExecOrderField, UserID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, Volume)
        .DEF_PROPERTY(CThostFtdcExecOrderField, RequestID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExecOrderField, OffsetFlag)
        .DEF_PROPERTY(CThostFtdcExecOrderField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ActionType)
        .DEF_PROPERTY(CThostFtdcExecOrderField, PosiDirection)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ReservePositionFlag)
        .DEF_PROPERTY(CThostFtdcExecOrderField, CloseFlag)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExecOrderLocalID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ClientID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, TraderID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, InstallID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, OrderSubmitStatus)
        .DEF_PROPERTY(CThostFtdcExecOrderField, NotifySequence)
        .DEF_PROPERTY(CThostFtdcExecOrderField, TradingDay)
        .DEF_PROPERTY(CThostFtdcExecOrderField, SettlementID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, InsertDate)
        .DEF_PROPERTY(CThostFtdcExecOrderField, InsertTime)
        .DEF_PROPERTY(CThostFtdcExecOrderField, CancelTime)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ExecResult)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ClearingPartID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, SequenceNo)
        .DEF_PROPERTY(CThostFtdcExecOrderField, FrontID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, SessionID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, UserProductInfo)
        .DEF_PROPERTY(CThostFtdcExecOrderField, StatusMsg)
        .DEF_PROPERTY(CThostFtdcExecOrderField, ActiveUserID)
        .DEF_PROPERTY(CThostFtdcExecOrderField, BrokerExecOrderSeq)
        .DEF_PROPERTY(CThostFtdcExecOrderField, BranchID)
    ;
}
void generate_class_CThostFtdcExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcExecOrderActionField>(m, "CThostFtdcExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ExecOrderActionRef)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, RequestID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, FrontID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, SessionID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ActionDate)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ActionTime)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, TraderID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, InstallID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ExecOrderLocalID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ActionLocalID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, OrderActionStatus)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, UserID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, ActionType)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, StatusMsg)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcExecOrderActionField, BranchID)
    ;
}
void generate_class_CThostFtdcQryExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExecOrderField>(m, "CThostFtdcQryExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, InsertTimeStart)
        .DEF_PROPERTY(CThostFtdcQryExecOrderField, InsertTimeEnd)
    ;
}
void generate_class_CThostFtdcExchangeExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcExchangeExecOrderField>(m, "CThostFtdcExchangeExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, Volume)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, RequestID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, OffsetFlag)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ActionType)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, PosiDirection)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ReservePositionFlag)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, CloseFlag)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ExecOrderLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ClientID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, TraderID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, InstallID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, OrderSubmitStatus)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, NotifySequence)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, TradingDay)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, SettlementID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, InsertDate)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, InsertTime)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, CancelTime)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ExecResult)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, ClearingPartID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, SequenceNo)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderField, BranchID)
    ;
}
void generate_class_CThostFtdcQryExchangeExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeExecOrderField>(m, "CThostFtdcQryExchangeExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderField, ClientID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderField, TraderID)
    ;
}
void generate_class_CThostFtdcQryExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExecOrderActionField>(m, "CThostFtdcQryExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExecOrderActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryExecOrderActionField, ExchangeID)
    ;
}
void generate_class_CThostFtdcExchangeExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcExchangeExecOrderActionField>(m, "CThostFtdcExchangeExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ActionDate)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ActionTime)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, TraderID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, InstallID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ExecOrderLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ActionLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, OrderActionStatus)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, UserID)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, ActionType)
        .DEF_PROPERTY(CThostFtdcExchangeExecOrderActionField, BranchID)
    ;
}
void generate_class_CThostFtdcQryExchangeExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeExecOrderActionField>(m, "CThostFtdcQryExchangeExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExchangeExecOrderActionField, TraderID)
    ;
}
void generate_class_CThostFtdcErrExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcErrExecOrderField>(m, "CThostFtdcErrExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, InvestorID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, UserID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, Volume)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, RequestID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, OffsetFlag)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, HedgeFlag)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ActionType)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, PosiDirection)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ReservePositionFlag)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, CloseFlag)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ErrorID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcQryErrExecOrderField(pybind11::module &m)
{
    py::class_<CThostFtdcQryErrExecOrderField>(m, "CThostFtdcQryErrExecOrderField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryErrExecOrderField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryErrExecOrderField, InvestorID)
    ;
}
void generate_class_CThostFtdcErrExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcErrExecOrderActionField>(m, "CThostFtdcErrExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ExecOrderActionRef)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ExecOrderRef)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, RequestID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, FrontID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, SessionID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ExecOrderSysID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, UserID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ErrorID)
        .DEF_PROPERTY(CThostFtdcErrExecOrderActionField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcQryErrExecOrderActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryErrExecOrderActionField>(m, "CThostFtdcQryErrExecOrderActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryErrExecOrderActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryErrExecOrderActionField, InvestorID)
    ;
}
void generate_class_CThostFtdcOptionInstrTradingRightField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrTradingRightField>(m, "CThostFtdcOptionInstrTradingRightField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, Direction)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, TradingRight)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcOptionInstrTradingRightField, HedgeFlag)
    ;
}
void generate_class_CThostFtdcQryOptionInstrTradingRightField(pybind11::module &m)
{
    py::class_<CThostFtdcQryOptionInstrTradingRightField>(m, "CThostFtdcQryOptionInstrTradingRightField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradingRightField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradingRightField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradingRightField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradingRightField, Direction)
        .DEF_PROPERTY(CThostFtdcQryOptionInstrTradingRightField, ExchangeID)
    ;
}
void generate_class_CThostFtdcInputForQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcInputForQuoteField>(m, "CThostFtdcInputForQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, ForQuoteRef)
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, UserID)
        .DEF_PROPERTY(CThostFtdcInputForQuoteField, ExchangeID)
    ;
}
void generate_class_CThostFtdcForQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcForQuoteField>(m, "CThostFtdcForQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcForQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ForQuoteRef)
        .DEF_PROPERTY(CThostFtdcForQuoteField, UserID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ForQuoteLocalID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, TraderID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, InstallID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, InsertDate)
        .DEF_PROPERTY(CThostFtdcForQuoteField, InsertTime)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ForQuoteStatus)
        .DEF_PROPERTY(CThostFtdcForQuoteField, FrontID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, SessionID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, StatusMsg)
        .DEF_PROPERTY(CThostFtdcForQuoteField, ActiveUserID)
        .DEF_PROPERTY(CThostFtdcForQuoteField, BrokerForQutoSeq)
    ;
}
void generate_class_CThostFtdcQryForQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcQryForQuoteField>(m, "CThostFtdcQryForQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, InsertTimeStart)
        .DEF_PROPERTY(CThostFtdcQryForQuoteField, InsertTimeEnd)
    ;
}
void generate_class_CThostFtdcExchangeForQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcExchangeForQuoteField>(m, "CThostFtdcExchangeForQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ForQuoteLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, TraderID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, InstallID)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, InsertDate)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, InsertTime)
        .DEF_PROPERTY(CThostFtdcExchangeForQuoteField, ForQuoteStatus)
    ;
}
void generate_class_CThostFtdcQryExchangeForQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeForQuoteField>(m, "CThostFtdcQryExchangeForQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeForQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryExchangeForQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcQryExchangeForQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcQryExchangeForQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExchangeForQuoteField, TraderID)
    ;
}
void generate_class_CThostFtdcInputQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcInputQuoteField>(m, "CThostFtdcInputQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, QuoteRef)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, UserID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, AskPrice)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BidPrice)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, AskVolume)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BidVolume)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, RequestID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, AskOffsetFlag)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BidOffsetFlag)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, AskHedgeFlag)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BidHedgeFlag)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, AskOrderRef)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, BidOrderRef)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, ForQuoteSysID)
        .DEF_PROPERTY(CThostFtdcInputQuoteField, ExchangeID)
    ;
}
void generate_class_CThostFtdcInputQuoteActionField(pybind11::module &m)
{
    py::class_<CThostFtdcInputQuoteActionField>(m, "CThostFtdcInputQuoteActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, QuoteActionRef)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, QuoteRef)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, RequestID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, FrontID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, SessionID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, UserID)
        .DEF_PROPERTY(CThostFtdcInputQuoteActionField, InstrumentID)
    ;
}
void generate_class_CThostFtdcQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcQuoteField>(m, "CThostFtdcQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQuoteField, QuoteRef)
        .DEF_PROPERTY(CThostFtdcQuoteField, UserID)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskPrice)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidPrice)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskVolume)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidVolume)
        .DEF_PROPERTY(CThostFtdcQuoteField, RequestID)
        .DEF_PROPERTY(CThostFtdcQuoteField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskOffsetFlag)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidOffsetFlag)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskHedgeFlag)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidHedgeFlag)
        .DEF_PROPERTY(CThostFtdcQuoteField, QuoteLocalID)
        .DEF_PROPERTY(CThostFtdcQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcQuoteField, TraderID)
        .DEF_PROPERTY(CThostFtdcQuoteField, InstallID)
        .DEF_PROPERTY(CThostFtdcQuoteField, NotifySequence)
        .DEF_PROPERTY(CThostFtdcQuoteField, OrderSubmitStatus)
        .DEF_PROPERTY(CThostFtdcQuoteField, TradingDay)
        .DEF_PROPERTY(CThostFtdcQuoteField, SettlementID)
        .DEF_PROPERTY(CThostFtdcQuoteField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcQuoteField, InsertDate)
        .DEF_PROPERTY(CThostFtdcQuoteField, InsertTime)
        .DEF_PROPERTY(CThostFtdcQuoteField, CancelTime)
        .DEF_PROPERTY(CThostFtdcQuoteField, QuoteStatus)
        .DEF_PROPERTY(CThostFtdcQuoteField, ClearingPartID)
        .DEF_PROPERTY(CThostFtdcQuoteField, SequenceNo)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskOrderSysID)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidOrderSysID)
        .DEF_PROPERTY(CThostFtdcQuoteField, FrontID)
        .DEF_PROPERTY(CThostFtdcQuoteField, SessionID)
        .DEF_PROPERTY(CThostFtdcQuoteField, UserProductInfo)
        .DEF_PROPERTY(CThostFtdcQuoteField, StatusMsg)
        .DEF_PROPERTY(CThostFtdcQuoteField, ActiveUserID)
        .DEF_PROPERTY(CThostFtdcQuoteField, BrokerQuoteSeq)
        .DEF_PROPERTY(CThostFtdcQuoteField, AskOrderRef)
        .DEF_PROPERTY(CThostFtdcQuoteField, BidOrderRef)
        .DEF_PROPERTY(CThostFtdcQuoteField, ForQuoteSysID)
        .DEF_PROPERTY(CThostFtdcQuoteField, BranchID)
    ;
}
void generate_class_CThostFtdcQuoteActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQuoteActionField>(m, "CThostFtdcQuoteActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQuoteActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, QuoteActionRef)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, QuoteRef)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, RequestID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, FrontID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, SessionID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ActionDate)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ActionTime)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, TraderID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, InstallID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, QuoteLocalID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ActionLocalID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, OrderActionStatus)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, UserID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, StatusMsg)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQuoteActionField, BranchID)
    ;
}
void generate_class_CThostFtdcQryQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcQryQuoteField>(m, "CThostFtdcQryQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryQuoteField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, InsertTimeStart)
        .DEF_PROPERTY(CThostFtdcQryQuoteField, InsertTimeEnd)
    ;
}
void generate_class_CThostFtdcExchangeQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcExchangeQuoteField>(m, "CThostFtdcExchangeQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, AskPrice)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BidPrice)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, AskVolume)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BidVolume)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, RequestID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, AskOffsetFlag)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BidOffsetFlag)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, AskHedgeFlag)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BidHedgeFlag)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, QuoteLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, TraderID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, InstallID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, NotifySequence)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, OrderSubmitStatus)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, TradingDay)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, SettlementID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, InsertDate)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, InsertTime)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, CancelTime)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, QuoteStatus)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ClearingPartID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, SequenceNo)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, AskOrderSysID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BidOrderSysID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, ForQuoteSysID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteField, BranchID)
    ;
}
void generate_class_CThostFtdcQryExchangeQuoteField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeQuoteField>(m, "CThostFtdcQryExchangeQuoteField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteField, ClientID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteField, ExchangeInstID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteField, TraderID)
    ;
}
void generate_class_CThostFtdcQryQuoteActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryQuoteActionField>(m, "CThostFtdcQryQuoteActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryQuoteActionField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryQuoteActionField, InvestorID)
        .DEF_PROPERTY(CThostFtdcQryQuoteActionField, ExchangeID)
    ;
}
void generate_class_CThostFtdcExchangeQuoteActionField(pybind11::module &m)
{
    py::class_<CThostFtdcExchangeQuoteActionField>(m, "CThostFtdcExchangeQuoteActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, QuoteSysID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ActionFlag)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ActionDate)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ActionTime)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, TraderID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, InstallID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, QuoteLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ActionLocalID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, BusinessUnit)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, OrderActionStatus)
        .DEF_PROPERTY(CThostFtdcExchangeQuoteActionField, UserID)
    ;
}
void generate_class_CThostFtdcQryExchangeQuoteActionField(pybind11::module &m)
{
    py::class_<CThostFtdcQryExchangeQuoteActionField>(m, "CThostFtdcQryExchangeQuoteActionField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteActionField, ParticipantID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteActionField, ClientID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteActionField, ExchangeID)
        .DEF_PROPERTY(CThostFtdcQryExchangeQuoteActionField, TraderID)
    ;
}
void generate_class_CThostFtdcOptionInstrDeltaField(pybind11::module &m)
{
    py::class_<CThostFtdcOptionInstrDeltaField>(m, "CThostFtdcOptionInstrDeltaField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, InvestorID)
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, Delta)
        .DEF_PROPERTY(CThostFtdcOptionInstrDeltaField, ExchangeID)
    ;
}
void generate_class_CThostFtdcForQuoteRspField(pybind11::module &m)
{
    py::class_<CThostFtdcForQuoteRspField>(m, "CThostFtdcForQuoteRspField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, TradingDay)
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, ForQuoteSysID)
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, ForQuoteTime)
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, ActionDay)
        .DEF_PROPERTY(CThostFtdcForQuoteRspField, ExchangeID)
    ;
}
void generate_class_CThostFtdcStrikeOffsetField(pybind11::module &m)
{
    py::class_<CThostFtdcStrikeOffsetField>(m, "CThostFtdcStrikeOffsetField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, InstrumentID)
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, InvestorRange)
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, BrokerID)
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, InvestorID)
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, Offset)
        .DEF_PROPERTY(CThostFtdcStrikeOffsetField, ExchangeID)
    ;
}

