#include <iostream>
#include <string>
#include <string_view>
#include <pybind11/pybind11.h>

#include "dispatcher.h"
#include "property_helper.h"
#include "wrapper_helper.h"
#include "class_generators.h"
#include "wrappers.h"

#include "ctp/ThostFtdcTraderApi.h"


void generate_class_CThostFtdcRspTransferField(pybind11::module &m)
{
    py::class_<CThostFtdcRspTransferField>(m, "CThostFtdcRspTransferField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspTransferField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspTransferField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspTransferField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspTransferField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, CustomerName)
        .DEF_PROPERTY(CThostFtdcRspTransferField, IdCardType)
        .DEF_PROPERTY(CThostFtdcRspTransferField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcRspTransferField, CustType)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankAccount)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcRspTransferField, AccountID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, Password)
        .DEF_PROPERTY(CThostFtdcRspTransferField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcRspTransferField, UserID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcRspTransferField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcRspTransferField, FutureFetchAmount)
        .DEF_PROPERTY(CThostFtdcRspTransferField, FeePayFlag)
        .DEF_PROPERTY(CThostFtdcRspTransferField, CustFee)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BrokerFee)
        .DEF_PROPERTY(CThostFtdcRspTransferField, Message)
        .DEF_PROPERTY(CThostFtdcRspTransferField, Digest)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankAccType)
        .DEF_PROPERTY(CThostFtdcRspTransferField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcRspTransferField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspTransferField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspTransferField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspTransferField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, TransferStatus)
        .DEF_PROPERTY(CThostFtdcRspTransferField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspTransferField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcReqRepealField(pybind11::module &m)
{
    py::class_<CThostFtdcReqRepealField>(m, "CThostFtdcReqRepealField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqRepealField, RepealTimeInterval)
        .DEF_PROPERTY(CThostFtdcReqRepealField, RepealedTimes)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankRepealFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BrokerRepealFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, PlateRepealSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankRepealSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, FutureRepealSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqRepealField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqRepealField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, CustomerName)
        .DEF_PROPERTY(CThostFtdcReqRepealField, IdCardType)
        .DEF_PROPERTY(CThostFtdcReqRepealField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcReqRepealField, CustType)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankAccount)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcReqRepealField, AccountID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, Password)
        .DEF_PROPERTY(CThostFtdcReqRepealField, InstallID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcReqRepealField, UserID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcReqRepealField, FutureFetchAmount)
        .DEF_PROPERTY(CThostFtdcReqRepealField, FeePayFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, CustFee)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BrokerFee)
        .DEF_PROPERTY(CThostFtdcReqRepealField, Message)
        .DEF_PROPERTY(CThostFtdcReqRepealField, Digest)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankAccType)
        .DEF_PROPERTY(CThostFtdcReqRepealField, DeviceID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcReqRepealField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcReqRepealField, OperNo)
        .DEF_PROPERTY(CThostFtdcReqRepealField, RequestID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TID)
        .DEF_PROPERTY(CThostFtdcReqRepealField, TransferStatus)
    ;
}
void generate_class_CThostFtdcRspRepealField(pybind11::module &m)
{
    py::class_<CThostFtdcRspRepealField>(m, "CThostFtdcRspRepealField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspRepealField, RepealTimeInterval)
        .DEF_PROPERTY(CThostFtdcRspRepealField, RepealedTimes)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankRepealFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BrokerRepealFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, PlateRepealSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankRepealSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, FutureRepealSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspRepealField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspRepealField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, CustomerName)
        .DEF_PROPERTY(CThostFtdcRspRepealField, IdCardType)
        .DEF_PROPERTY(CThostFtdcRspRepealField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcRspRepealField, CustType)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankAccount)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcRspRepealField, AccountID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, Password)
        .DEF_PROPERTY(CThostFtdcRspRepealField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcRspRepealField, UserID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcRspRepealField, FutureFetchAmount)
        .DEF_PROPERTY(CThostFtdcRspRepealField, FeePayFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, CustFee)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BrokerFee)
        .DEF_PROPERTY(CThostFtdcRspRepealField, Message)
        .DEF_PROPERTY(CThostFtdcRspRepealField, Digest)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankAccType)
        .DEF_PROPERTY(CThostFtdcRspRepealField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcRspRepealField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspRepealField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspRepealField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, TransferStatus)
        .DEF_PROPERTY(CThostFtdcRspRepealField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspRepealField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcReqQueryAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcReqQueryAccountField>(m, "CThostFtdcReqQueryAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, Password)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, UserID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, DeviceID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, OperNo)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, RequestID)
        .DEF_PROPERTY(CThostFtdcReqQueryAccountField, TID)
    ;
}
void generate_class_CThostFtdcRspQueryAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcRspQueryAccountField>(m, "CThostFtdcRspQueryAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, Password)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, UserID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, TID)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankUseAmount)
        .DEF_PROPERTY(CThostFtdcRspQueryAccountField, BankFetchAmount)
    ;
}
void generate_class_CThostFtdcFutureSignIOField(pybind11::module &m)
{
    py::class_<CThostFtdcFutureSignIOField>(m, "CThostFtdcFutureSignIOField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, TradeCode)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BankID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BrokerID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, TradeDate)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, TradeTime)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BankSerial)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, TradingDay)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, LastFragment)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, SessionID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, InstallID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, UserID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, Digest)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, DeviceID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, OperNo)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, RequestID)
        .DEF_PROPERTY(CThostFtdcFutureSignIOField, TID)
    ;
}
void generate_class_CThostFtdcRspFutureSignInField(pybind11::module &m)
{
    py::class_<CThostFtdcRspFutureSignInField>(m, "CThostFtdcRspFutureSignInField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BankID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, UserID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, Digest)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, TID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, ErrorMsg)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, PinKey)
        .DEF_PROPERTY(CThostFtdcRspFutureSignInField, MacKey)
    ;
}
void generate_class_CThostFtdcReqFutureSignOutField(pybind11::module &m)
{
    py::class_<CThostFtdcReqFutureSignOutField>(m, "CThostFtdcReqFutureSignOutField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BankID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, InstallID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, UserID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, Digest)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, DeviceID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, OperNo)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, RequestID)
        .DEF_PROPERTY(CThostFtdcReqFutureSignOutField, TID)
    ;
}
void generate_class_CThostFtdcRspFutureSignOutField(pybind11::module &m)
{
    py::class_<CThostFtdcRspFutureSignOutField>(m, "CThostFtdcRspFutureSignOutField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BankID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, UserID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, Digest)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, TID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspFutureSignOutField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcReqQueryTradeResultBySerialField(pybind11::module &m)
{
    py::class_<CThostFtdcReqQueryTradeResultBySerialField>(m, "CThostFtdcReqQueryTradeResultBySerialField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BankID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, Reference)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, RefrenceIssureType)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, RefrenceIssure)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, CustomerName)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, IdCardType)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, CustType)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BankAccount)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, AccountID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, Password)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcReqQueryTradeResultBySerialField, Digest)
    ;
}
void generate_class_CThostFtdcRspQueryTradeResultBySerialField(pybind11::module &m)
{
    py::class_<CThostFtdcRspQueryTradeResultBySerialField>(m, "CThostFtdcRspQueryTradeResultBySerialField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BankID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, ErrorMsg)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, Reference)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, RefrenceIssureType)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, RefrenceIssure)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, OriginReturnCode)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, OriginDescrInfoForReturnCode)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BankAccount)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, AccountID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, Password)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcRspQueryTradeResultBySerialField, Digest)
    ;
}
void generate_class_CThostFtdcReqDayEndFileReadyField(pybind11::module &m)
{
    py::class_<CThostFtdcReqDayEndFileReadyField>(m, "CThostFtdcReqDayEndFileReadyField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, BankID)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, FileBusinessCode)
        .DEF_PROPERTY(CThostFtdcReqDayEndFileReadyField, Digest)
    ;
}
void generate_class_CThostFtdcReturnResultField(pybind11::module &m)
{
    py::class_<CThostFtdcReturnResultField>(m, "CThostFtdcReturnResultField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReturnResultField, ReturnCode)
        .DEF_PROPERTY(CThostFtdcReturnResultField, DescrInfoForReturnCode)
    ;
}
void generate_class_CThostFtdcVerifyFuturePasswordField(pybind11::module &m)
{
    py::class_<CThostFtdcVerifyFuturePasswordField>(m, "CThostFtdcVerifyFuturePasswordField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, TradeCode)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BankID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BrokerID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, TradeDate)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, TradeTime)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BankSerial)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, TradingDay)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, LastFragment)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, SessionID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, AccountID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, Password)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BankAccount)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, InstallID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, TID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordField, CurrencyID)
    ;
}
void generate_class_CThostFtdcVerifyCustInfoField(pybind11::module &m)
{
    py::class_<CThostFtdcVerifyCustInfoField>(m, "CThostFtdcVerifyCustInfoField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcVerifyCustInfoField, CustomerName)
        .DEF_PROPERTY(CThostFtdcVerifyCustInfoField, IdCardType)
        .DEF_PROPERTY(CThostFtdcVerifyCustInfoField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcVerifyCustInfoField, CustType)
    ;
}
void generate_class_CThostFtdcVerifyFuturePasswordAndCustInfoField(pybind11::module &m)
{
    py::class_<CThostFtdcVerifyFuturePasswordAndCustInfoField>(m, "CThostFtdcVerifyFuturePasswordAndCustInfoField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, CustomerName)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, IdCardType)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, CustType)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, AccountID)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, Password)
        .DEF_PROPERTY(CThostFtdcVerifyFuturePasswordAndCustInfoField, CurrencyID)
    ;
}
void generate_class_CThostFtdcDepositResultInformField(pybind11::module &m)
{
    py::class_<CThostFtdcDepositResultInformField>(m, "CThostFtdcDepositResultInformField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, DepositSeqNo)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, BrokerID)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, InvestorID)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, Deposit)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, RequestID)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, ReturnCode)
        .DEF_PROPERTY(CThostFtdcDepositResultInformField, DescrInfoForReturnCode)
    ;
}
void generate_class_CThostFtdcReqSyncKeyField(pybind11::module &m)
{
    py::class_<CThostFtdcReqSyncKeyField>(m, "CThostFtdcReqSyncKeyField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, TradeCode)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BankID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BrokerID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, TradeDate)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, TradeTime)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BankSerial)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, TradingDay)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, LastFragment)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, SessionID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, InstallID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, UserID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, Message)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, DeviceID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, OperNo)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, RequestID)
        .DEF_PROPERTY(CThostFtdcReqSyncKeyField, TID)
    ;
}
void generate_class_CThostFtdcRspSyncKeyField(pybind11::module &m)
{
    py::class_<CThostFtdcRspSyncKeyField>(m, "CThostFtdcRspSyncKeyField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, TradeCode)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BankID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BrokerID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, TradeDate)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, TradeTime)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BankSerial)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, TradingDay)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, LastFragment)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, SessionID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, InstallID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, UserID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, Message)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, DeviceID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, OperNo)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, RequestID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, TID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, ErrorID)
        .DEF_PROPERTY(CThostFtdcRspSyncKeyField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcNotifyQueryAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcNotifyQueryAccountField>(m, "CThostFtdcNotifyQueryAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, Password)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, UserID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, DeviceID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, OperNo)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, RequestID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, TID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankUseAmount)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, BankFetchAmount)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, ErrorID)
        .DEF_PROPERTY(CThostFtdcNotifyQueryAccountField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcTransferSerialField(pybind11::module &m)
{
    py::class_<CThostFtdcTransferSerialField>(m, "CThostFtdcTransferSerialField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcTransferSerialField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, TradeDate)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, TradingDay)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, TradeTime)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, TradeCode)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, SessionID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankAccType)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankAccount)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankSerial)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BrokerID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, FutureAccType)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, AccountID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, InvestorID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, FutureSerial)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, IdCardType)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, TradeAmount)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, CustFee)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BrokerFee)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, AvailabilityFlag)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, OperatorCode)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, BankNewAccount)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, ErrorID)
        .DEF_PROPERTY(CThostFtdcTransferSerialField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcQryTransferSerialField(pybind11::module &m)
{
    py::class_<CThostFtdcQryTransferSerialField>(m, "CThostFtdcQryTransferSerialField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryTransferSerialField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryTransferSerialField, AccountID)
        .DEF_PROPERTY(CThostFtdcQryTransferSerialField, BankID)
        .DEF_PROPERTY(CThostFtdcQryTransferSerialField, CurrencyID)
    ;
}
void generate_class_CThostFtdcNotifyFutureSignInField(pybind11::module &m)
{
    py::class_<CThostFtdcNotifyFutureSignInField>(m, "CThostFtdcNotifyFutureSignInField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, TradeCode)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BankID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BrokerID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, TradeDate)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, TradeTime)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BankSerial)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, TradingDay)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, LastFragment)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, SessionID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, InstallID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, UserID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, Digest)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, DeviceID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, OperNo)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, RequestID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, TID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, ErrorID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, ErrorMsg)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, PinKey)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignInField, MacKey)
    ;
}
void generate_class_CThostFtdcNotifyFutureSignOutField(pybind11::module &m)
{
    py::class_<CThostFtdcNotifyFutureSignOutField>(m, "CThostFtdcNotifyFutureSignOutField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, TradeCode)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BankID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BrokerID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, TradeDate)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, TradeTime)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BankSerial)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, TradingDay)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, LastFragment)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, SessionID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, InstallID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, UserID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, Digest)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, DeviceID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, OperNo)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, RequestID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, TID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, ErrorID)
        .DEF_PROPERTY(CThostFtdcNotifyFutureSignOutField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcNotifySyncKeyField(pybind11::module &m)
{
    py::class_<CThostFtdcNotifySyncKeyField>(m, "CThostFtdcNotifySyncKeyField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, TradeCode)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BankID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BrokerID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, TradeDate)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, TradeTime)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BankSerial)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, TradingDay)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, LastFragment)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, SessionID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, InstallID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, UserID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, Message)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, DeviceID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, OperNo)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, RequestID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, TID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, ErrorID)
        .DEF_PROPERTY(CThostFtdcNotifySyncKeyField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcQryAccountregisterField(pybind11::module &m)
{
    py::class_<CThostFtdcQryAccountregisterField>(m, "CThostFtdcQryAccountregisterField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryAccountregisterField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryAccountregisterField, AccountID)
        .DEF_PROPERTY(CThostFtdcQryAccountregisterField, BankID)
        .DEF_PROPERTY(CThostFtdcQryAccountregisterField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcQryAccountregisterField, CurrencyID)
    ;
}
void generate_class_CThostFtdcAccountregisterField(pybind11::module &m)
{
    py::class_<CThostFtdcAccountregisterField>(m, "CThostFtdcAccountregisterField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcAccountregisterField, TradeDay)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BankID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BankAccount)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BrokerID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, AccountID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, IdCardType)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, CustomerName)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, OpenOrDestroy)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, RegDate)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, OutDate)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, TID)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, CustType)
        .DEF_PROPERTY(CThostFtdcAccountregisterField, BankAccType)
    ;
}
void generate_class_CThostFtdcOpenAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcOpenAccountField>(m, "CThostFtdcOpenAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcOpenAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Gender)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, CountryCode)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Address)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, ZipCode)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Telephone)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, MobilePhone)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Fax)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, EMail)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, MoneyAccountStatus)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Password)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, CashExchangeCode)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, DeviceID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, OperNo)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, TID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, UserID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, ErrorID)
        .DEF_PROPERTY(CThostFtdcOpenAccountField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcCancelAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcCancelAccountField>(m, "CThostFtdcCancelAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcCancelAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Gender)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, CountryCode)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Address)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, ZipCode)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Telephone)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, MobilePhone)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Fax)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, EMail)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, MoneyAccountStatus)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Password)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, CashExchangeCode)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, DeviceID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankSecuAccType)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankSecuAcc)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, OperNo)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, TID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, UserID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, ErrorID)
        .DEF_PROPERTY(CThostFtdcCancelAccountField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcChangeAccountField(pybind11::module &m)
{
    py::class_<CThostFtdcChangeAccountField>(m, "CThostFtdcChangeAccountField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcChangeAccountField, TradeCode)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankBranchID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BrokerID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BrokerBranchID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, TradeDate)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, TradeTime)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankSerial)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, TradingDay)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, PlateSerial)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, LastFragment)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, SessionID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, CustomerName)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, IdCardType)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, IdentifiedCardNo)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Gender)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, CountryCode)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, CustType)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Address)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, ZipCode)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Telephone)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, MobilePhone)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Fax)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, EMail)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, MoneyAccountStatus)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankAccount)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankPassWord)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, NewBankAccount)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, NewBankPassWord)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, AccountID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Password)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankAccType)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, InstallID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, VerifyCertNoFlag)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BrokerIDByBank)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, BankPwdFlag)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, SecuPwdFlag)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, TID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, Digest)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, ErrorID)
        .DEF_PROPERTY(CThostFtdcChangeAccountField, ErrorMsg)
    ;
}
void generate_class_CThostFtdcSecAgentACIDMapField(pybind11::module &m)
{
    py::class_<CThostFtdcSecAgentACIDMapField>(m, "CThostFtdcSecAgentACIDMapField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcSecAgentACIDMapField, BrokerID)
        .DEF_PROPERTY(CThostFtdcSecAgentACIDMapField, UserID)
        .DEF_PROPERTY(CThostFtdcSecAgentACIDMapField, AccountID)
        .DEF_PROPERTY(CThostFtdcSecAgentACIDMapField, CurrencyID)
        .DEF_PROPERTY(CThostFtdcSecAgentACIDMapField, BrokerSecAgentID)
    ;
}
void generate_class_CThostFtdcQrySecAgentACIDMapField(pybind11::module &m)
{
    py::class_<CThostFtdcQrySecAgentACIDMapField>(m, "CThostFtdcQrySecAgentACIDMapField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQrySecAgentACIDMapField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQrySecAgentACIDMapField, UserID)
        .DEF_PROPERTY(CThostFtdcQrySecAgentACIDMapField, AccountID)
        .DEF_PROPERTY(CThostFtdcQrySecAgentACIDMapField, CurrencyID)
    ;
}
void generate_class_CThostFtdcUserRightsAssignField(pybind11::module &m)
{
    py::class_<CThostFtdcUserRightsAssignField>(m, "CThostFtdcUserRightsAssignField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcUserRightsAssignField, BrokerID)
        .DEF_PROPERTY(CThostFtdcUserRightsAssignField, UserID)
        .DEF_PROPERTY(CThostFtdcUserRightsAssignField, DRIdentityID)
    ;
}
void generate_class_CThostFtdcBrokerUserRightAssignField(pybind11::module &m)
{
    py::class_<CThostFtdcBrokerUserRightAssignField>(m, "CThostFtdcBrokerUserRightAssignField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcBrokerUserRightAssignField, BrokerID)
        .DEF_PROPERTY(CThostFtdcBrokerUserRightAssignField, DRIdentityID)
        .DEF_PROPERTY(CThostFtdcBrokerUserRightAssignField, Tradeable)
    ;
}
void generate_class_CThostFtdcDRTransferField(pybind11::module &m)
{
    py::class_<CThostFtdcDRTransferField>(m, "CThostFtdcDRTransferField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcDRTransferField, OrigDRIdentityID)
        .DEF_PROPERTY(CThostFtdcDRTransferField, DestDRIdentityID)
        .DEF_PROPERTY(CThostFtdcDRTransferField, OrigBrokerID)
        .DEF_PROPERTY(CThostFtdcDRTransferField, DestBrokerID)
    ;
}
void generate_class_CThostFtdcFensUserInfoField(pybind11::module &m)
{
    py::class_<CThostFtdcFensUserInfoField>(m, "CThostFtdcFensUserInfoField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcFensUserInfoField, BrokerID)
        .DEF_PROPERTY(CThostFtdcFensUserInfoField, UserID)
        .DEF_PROPERTY(CThostFtdcFensUserInfoField, LoginMode)
    ;
}
void generate_class_CThostFtdcCurrTransferIdentityField(pybind11::module &m)
{
    py::class_<CThostFtdcCurrTransferIdentityField>(m, "CThostFtdcCurrTransferIdentityField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcCurrTransferIdentityField, IdentityID)
    ;
}
void generate_class_CThostFtdcLoginForbiddenUserField(pybind11::module &m)
{
    py::class_<CThostFtdcLoginForbiddenUserField>(m, "CThostFtdcLoginForbiddenUserField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcLoginForbiddenUserField, BrokerID)
        .DEF_PROPERTY(CThostFtdcLoginForbiddenUserField, UserID)
        .DEF_PROPERTY(CThostFtdcLoginForbiddenUserField, IPAddress)
    ;
}
void generate_class_CThostFtdcQryLoginForbiddenUserField(pybind11::module &m)
{
    py::class_<CThostFtdcQryLoginForbiddenUserField>(m, "CThostFtdcQryLoginForbiddenUserField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcQryLoginForbiddenUserField, BrokerID)
        .DEF_PROPERTY(CThostFtdcQryLoginForbiddenUserField, UserID)
    ;
}
void generate_class_CThostFtdcMulticastGroupInfoField(pybind11::module &m)
{
    py::class_<CThostFtdcMulticastGroupInfoField>(m, "CThostFtdcMulticastGroupInfoField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcMulticastGroupInfoField, GroupIP)
        .DEF_PROPERTY(CThostFtdcMulticastGroupInfoField, GroupPort)
        .DEF_PROPERTY(CThostFtdcMulticastGroupInfoField, SourceIP)
    ;
}
void generate_class_CThostFtdcTradingAccountReserveField(pybind11::module &m)
{
    py::class_<CThostFtdcTradingAccountReserveField>(m, "CThostFtdcTradingAccountReserveField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcTradingAccountReserveField, BrokerID)
        .DEF_PROPERTY(CThostFtdcTradingAccountReserveField, AccountID)
        .DEF_PROPERTY(CThostFtdcTradingAccountReserveField, Reserve)
        .DEF_PROPERTY(CThostFtdcTradingAccountReserveField, CurrencyID)
    ;
}
void generate_class_CThostFtdcDBFRecordField(pybind11::module &m)
{
    py::class_<CThostFtdcDBFRecordField>(m, "CThostFtdcDBFRecordField")
        .def(py::init<>())
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFComdType)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFComTime)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFOComNo)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFComNo)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdName1)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdContent1)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdName2)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdContent2)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdName3)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdContent3)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdName4)
        .DEF_PROPERTY(CThostFtdcDBFRecordField, DBFFdContent4)
    ;
}
void generate_class_CThostFtdcTraderSpi(pybind11::module &m)
{
    py::class_<
        CThostFtdcTraderSpi,
        std::unique_ptr<CThostFtdcTraderSpi, pybind11::nodelete>,
        PyCThostFtdcTraderSpi
    >(m, "CThostFtdcTraderSpi")
        .def(py::init<>())
        .def("OnFrontConnected", &CThostFtdcTraderSpi::OnFrontConnected)
        .def("OnFrontDisconnected", &CThostFtdcTraderSpi::OnFrontDisconnected)
        .def("OnHeartBeatWarning", &CThostFtdcTraderSpi::OnHeartBeatWarning)
        .def("OnRspAuthenticate", &CThostFtdcTraderSpi::OnRspAuthenticate)
        .def("OnRspUserLogin", &CThostFtdcTraderSpi::OnRspUserLogin)
        .def("OnRspUserLogout", &CThostFtdcTraderSpi::OnRspUserLogout)
        .def("OnRspUserPasswordUpdate", &CThostFtdcTraderSpi::OnRspUserPasswordUpdate)
        .def("OnRspTradingAccountPasswordUpdate", &CThostFtdcTraderSpi::OnRspTradingAccountPasswordUpdate)
        .def("OnRspOrderInsert", &CThostFtdcTraderSpi::OnRspOrderInsert)
        .def("OnRspParkedOrderInsert", &CThostFtdcTraderSpi::OnRspParkedOrderInsert)
        .def("OnRspParkedOrderAction", &CThostFtdcTraderSpi::OnRspParkedOrderAction)
        .def("OnRspOrderAction", &CThostFtdcTraderSpi::OnRspOrderAction)
        .def("OnRspQueryMaxOrderVolume", &CThostFtdcTraderSpi::OnRspQueryMaxOrderVolume)
        .def("OnRspSettlementInfoConfirm", &CThostFtdcTraderSpi::OnRspSettlementInfoConfirm)
        .def("OnRspRemoveParkedOrder", &CThostFtdcTraderSpi::OnRspRemoveParkedOrder)
        .def("OnRspRemoveParkedOrderAction", &CThostFtdcTraderSpi::OnRspRemoveParkedOrderAction)
        .def("OnRspExecOrderInsert", &CThostFtdcTraderSpi::OnRspExecOrderInsert)
        .def("OnRspExecOrderAction", &CThostFtdcTraderSpi::OnRspExecOrderAction)
        .def("OnRspForQuoteInsert", &CThostFtdcTraderSpi::OnRspForQuoteInsert)
        .def("OnRspQuoteInsert", &CThostFtdcTraderSpi::OnRspQuoteInsert)
        .def("OnRspQuoteAction", &CThostFtdcTraderSpi::OnRspQuoteAction)
        .def("OnRspLockInsert", &CThostFtdcTraderSpi::OnRspLockInsert)
        .def("OnRspCombActionInsert", &CThostFtdcTraderSpi::OnRspCombActionInsert)
        .def("OnRspQryOrder", &CThostFtdcTraderSpi::OnRspQryOrder)
        .def("OnRspQryTrade", &CThostFtdcTraderSpi::OnRspQryTrade)
        .def("OnRspQryInvestorPosition", &CThostFtdcTraderSpi::OnRspQryInvestorPosition)
        .def("OnRspQryTradingAccount", &CThostFtdcTraderSpi::OnRspQryTradingAccount)
        .def("OnRspQryInvestor", &CThostFtdcTraderSpi::OnRspQryInvestor)
        .def("OnRspQryTradingCode", &CThostFtdcTraderSpi::OnRspQryTradingCode)
        .def("OnRspQryInstrumentMarginRate", &CThostFtdcTraderSpi::OnRspQryInstrumentMarginRate)
        .def("OnRspQryInstrumentCommissionRate", &CThostFtdcTraderSpi::OnRspQryInstrumentCommissionRate)
        .def("OnRspQryExchange", &CThostFtdcTraderSpi::OnRspQryExchange)
        .def("OnRspQryProduct", &CThostFtdcTraderSpi::OnRspQryProduct)
        .def("OnRspQryInstrument", &CThostFtdcTraderSpi::OnRspQryInstrument)
        .def("OnRspQryDepthMarketData", &CThostFtdcTraderSpi::OnRspQryDepthMarketData)
        .def("OnRspQrySettlementInfo", &CThostFtdcTraderSpi::OnRspQrySettlementInfo)
        .def("OnRspQryTransferBank", &CThostFtdcTraderSpi::OnRspQryTransferBank)
        .def("OnRspQryInvestorPositionDetail", &CThostFtdcTraderSpi::OnRspQryInvestorPositionDetail)
        .def("OnRspQryNotice", &CThostFtdcTraderSpi::OnRspQryNotice)
        .def("OnRspQrySettlementInfoConfirm", &CThostFtdcTraderSpi::OnRspQrySettlementInfoConfirm)
        .def("OnRspQryInvestorPositionCombineDetail", &CThostFtdcTraderSpi::OnRspQryInvestorPositionCombineDetail)
        .def("OnRspQryCFMMCTradingAccountKey", &CThostFtdcTraderSpi::OnRspQryCFMMCTradingAccountKey)
        .def("OnRspQryEWarrantOffset", &CThostFtdcTraderSpi::OnRspQryEWarrantOffset)
        .def("OnRspQryInvestorProductGroupMargin", &CThostFtdcTraderSpi::OnRspQryInvestorProductGroupMargin)
        .def("OnRspQryExchangeMarginRate", &CThostFtdcTraderSpi::OnRspQryExchangeMarginRate)
        .def("OnRspQryExchangeMarginRateAdjust", &CThostFtdcTraderSpi::OnRspQryExchangeMarginRateAdjust)
        .def("OnRspQryExchangeRate", &CThostFtdcTraderSpi::OnRspQryExchangeRate)
        .def("OnRspQrySecAgentACIDMap", &CThostFtdcTraderSpi::OnRspQrySecAgentACIDMap)
        .def("OnRspQryProductExchRate", &CThostFtdcTraderSpi::OnRspQryProductExchRate)
        .def("OnRspQryProductGroup", &CThostFtdcTraderSpi::OnRspQryProductGroup)
        .def("OnRspQryOptionInstrTradeCost", &CThostFtdcTraderSpi::OnRspQryOptionInstrTradeCost)
        .def("OnRspQryOptionInstrCommRate", &CThostFtdcTraderSpi::OnRspQryOptionInstrCommRate)
        .def("OnRspQryExecOrder", &CThostFtdcTraderSpi::OnRspQryExecOrder)
        .def("OnRspQryForQuote", &CThostFtdcTraderSpi::OnRspQryForQuote)
        .def("OnRspQryQuote", &CThostFtdcTraderSpi::OnRspQryQuote)
        .def("OnRspQryLock", &CThostFtdcTraderSpi::OnRspQryLock)
        .def("OnRspQryLockPosition", &CThostFtdcTraderSpi::OnRspQryLockPosition)
        .def("OnRspQryInvestorLevel", &CThostFtdcTraderSpi::OnRspQryInvestorLevel)
        .def("OnRspQryExecFreeze", &CThostFtdcTraderSpi::OnRspQryExecFreeze)
        .def("OnRspQryCombInstrumentGuard", &CThostFtdcTraderSpi::OnRspQryCombInstrumentGuard)
        .def("OnRspQryCombAction", &CThostFtdcTraderSpi::OnRspQryCombAction)
        .def("OnRspQryTransferSerial", &CThostFtdcTraderSpi::OnRspQryTransferSerial)
        .def("OnRspQryAccountregister", &CThostFtdcTraderSpi::OnRspQryAccountregister)
        .def("OnRspError", &CThostFtdcTraderSpi::OnRspError)
        .def("OnRtnOrder", &CThostFtdcTraderSpi::OnRtnOrder)
        .def("OnRtnTrade", &CThostFtdcTraderSpi::OnRtnTrade)
        .def("OnErrRtnOrderInsert", &CThostFtdcTraderSpi::OnErrRtnOrderInsert)
        .def("OnErrRtnOrderAction", &CThostFtdcTraderSpi::OnErrRtnOrderAction)
        .def("OnRtnInstrumentStatus", &CThostFtdcTraderSpi::OnRtnInstrumentStatus)
        .def("OnRtnTradingNotice", &CThostFtdcTraderSpi::OnRtnTradingNotice)
        .def("OnRtnErrorConditionalOrder", &CThostFtdcTraderSpi::OnRtnErrorConditionalOrder)
        .def("OnRtnExecOrder", &CThostFtdcTraderSpi::OnRtnExecOrder)
        .def("OnErrRtnExecOrderInsert", &CThostFtdcTraderSpi::OnErrRtnExecOrderInsert)
        .def("OnErrRtnExecOrderAction", &CThostFtdcTraderSpi::OnErrRtnExecOrderAction)
        .def("OnErrRtnForQuoteInsert", &CThostFtdcTraderSpi::OnErrRtnForQuoteInsert)
        .def("OnRtnQuote", &CThostFtdcTraderSpi::OnRtnQuote)
        .def("OnErrRtnQuoteInsert", &CThostFtdcTraderSpi::OnErrRtnQuoteInsert)
        .def("OnErrRtnQuoteAction", &CThostFtdcTraderSpi::OnErrRtnQuoteAction)
        .def("OnRtnForQuoteRsp", &CThostFtdcTraderSpi::OnRtnForQuoteRsp)
        .def("OnRtnCFMMCTradingAccountToken", &CThostFtdcTraderSpi::OnRtnCFMMCTradingAccountToken)
        .def("OnRtnLock", &CThostFtdcTraderSpi::OnRtnLock)
        .def("OnErrRtnLockInsert", &CThostFtdcTraderSpi::OnErrRtnLockInsert)
        .def("OnRtnCombAction", &CThostFtdcTraderSpi::OnRtnCombAction)
        .def("OnErrRtnCombActionInsert", &CThostFtdcTraderSpi::OnErrRtnCombActionInsert)
        .def("OnRspQryContractBank", &CThostFtdcTraderSpi::OnRspQryContractBank)
        .def("OnRspQryParkedOrder", &CThostFtdcTraderSpi::OnRspQryParkedOrder)
        .def("OnRspQryParkedOrderAction", &CThostFtdcTraderSpi::OnRspQryParkedOrderAction)
        .def("OnRspQryTradingNotice", &CThostFtdcTraderSpi::OnRspQryTradingNotice)
        .def("OnRspQryBrokerTradingParams", &CThostFtdcTraderSpi::OnRspQryBrokerTradingParams)
        .def("OnRspQryBrokerTradingAlgos", &CThostFtdcTraderSpi::OnRspQryBrokerTradingAlgos)
        .def("OnRspQueryCFMMCTradingAccountToken", &CThostFtdcTraderSpi::OnRspQueryCFMMCTradingAccountToken)
        .def("OnRtnFromBankToFutureByBank", &CThostFtdcTraderSpi::OnRtnFromBankToFutureByBank)
        .def("OnRtnFromFutureToBankByBank", &CThostFtdcTraderSpi::OnRtnFromFutureToBankByBank)
        .def("OnRtnRepealFromBankToFutureByBank", &CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByBank)
        .def("OnRtnRepealFromFutureToBankByBank", &CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByBank)
        .def("OnRtnFromBankToFutureByFuture", &CThostFtdcTraderSpi::OnRtnFromBankToFutureByFuture)
        .def("OnRtnFromFutureToBankByFuture", &CThostFtdcTraderSpi::OnRtnFromFutureToBankByFuture)
        .def("OnRtnRepealFromBankToFutureByFutureManual", &CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByFutureManual)
        .def("OnRtnRepealFromFutureToBankByFutureManual", &CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByFutureManual)
        .def("OnRtnQueryBankBalanceByFuture", &CThostFtdcTraderSpi::OnRtnQueryBankBalanceByFuture)
        .def("OnErrRtnBankToFutureByFuture", &CThostFtdcTraderSpi::OnErrRtnBankToFutureByFuture)
        .def("OnErrRtnFutureToBankByFuture", &CThostFtdcTraderSpi::OnErrRtnFutureToBankByFuture)
        .def("OnErrRtnRepealBankToFutureByFutureManual", &CThostFtdcTraderSpi::OnErrRtnRepealBankToFutureByFutureManual)
        .def("OnErrRtnRepealFutureToBankByFutureManual", &CThostFtdcTraderSpi::OnErrRtnRepealFutureToBankByFutureManual)
        .def("OnErrRtnQueryBankBalanceByFuture", &CThostFtdcTraderSpi::OnErrRtnQueryBankBalanceByFuture)
        .def("OnRtnRepealFromBankToFutureByFuture", &CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByFuture)
        .def("OnRtnRepealFromFutureToBankByFuture", &CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByFuture)
        .def("OnRspFromBankToFutureByFuture", &CThostFtdcTraderSpi::OnRspFromBankToFutureByFuture)
        .def("OnRspFromFutureToBankByFuture", &CThostFtdcTraderSpi::OnRspFromFutureToBankByFuture)
        .def("OnRspQueryBankAccountMoneyByFuture", &CThostFtdcTraderSpi::OnRspQueryBankAccountMoneyByFuture)
        .def("OnRtnOpenAccountByBank", &CThostFtdcTraderSpi::OnRtnOpenAccountByBank)
        .def("OnRtnCancelAccountByBank", &CThostFtdcTraderSpi::OnRtnCancelAccountByBank)
        .def("OnRtnChangeAccountByBank", &CThostFtdcTraderSpi::OnRtnChangeAccountByBank)
    ;
}
void generate_class_CThostFtdcTraderApi(pybind11::module &m)
{
    py::class_<
        CThostFtdcTraderApi,
        std::unique_ptr<CThostFtdcTraderApi, pybind11::nodelete>,
        PyCThostFtdcTraderApi
    >(m, "CThostFtdcTraderApi")
        .def_static("CreateFtdcTraderApi", &CThostFtdcTraderApi::CreateFtdcTraderApi)
        .def_static("GetApiVersion", &CThostFtdcTraderApi::GetApiVersion)
        .def("Release", &CThostFtdcTraderApi::Release)
        .def("Init", &CThostFtdcTraderApi::Init)
        .def("Join", &CThostFtdcTraderApi::Join)
        .def("GetTradingDay", &CThostFtdcTraderApi::GetTradingDay)
        .def("RegisterFront", &CThostFtdcTraderApi::RegisterFront)
        .def("RegisterNameServer", &CThostFtdcTraderApi::RegisterNameServer)
        .def("RegisterFensUserInfo", &CThostFtdcTraderApi::RegisterFensUserInfo)
        .def("RegisterSpi", &CThostFtdcTraderApi::RegisterSpi)
        .def("SubscribePrivateTopic", &CThostFtdcTraderApi::SubscribePrivateTopic)
        .def("SubscribePublicTopic", &CThostFtdcTraderApi::SubscribePublicTopic)
        .def("ReqAuthenticate", &CThostFtdcTraderApi::ReqAuthenticate)
        .def("ReqUserLogin", &CThostFtdcTraderApi::ReqUserLogin)
        .def("ReqUserLogout", &CThostFtdcTraderApi::ReqUserLogout)
        .def("ReqUserPasswordUpdate", &CThostFtdcTraderApi::ReqUserPasswordUpdate)
        .def("ReqTradingAccountPasswordUpdate", &CThostFtdcTraderApi::ReqTradingAccountPasswordUpdate)
        .def("ReqOrderInsert", &CThostFtdcTraderApi::ReqOrderInsert)
        .def("ReqParkedOrderInsert", &CThostFtdcTraderApi::ReqParkedOrderInsert)
        .def("ReqParkedOrderAction", &CThostFtdcTraderApi::ReqParkedOrderAction)
        .def("ReqOrderAction", &CThostFtdcTraderApi::ReqOrderAction)
        .def("ReqQueryMaxOrderVolume", &CThostFtdcTraderApi::ReqQueryMaxOrderVolume)
        .def("ReqSettlementInfoConfirm", &CThostFtdcTraderApi::ReqSettlementInfoConfirm)
        .def("ReqRemoveParkedOrder", &CThostFtdcTraderApi::ReqRemoveParkedOrder)
        .def("ReqRemoveParkedOrderAction", &CThostFtdcTraderApi::ReqRemoveParkedOrderAction)
        .def("ReqExecOrderInsert", &CThostFtdcTraderApi::ReqExecOrderInsert)
        .def("ReqExecOrderAction", &CThostFtdcTraderApi::ReqExecOrderAction)
        .def("ReqForQuoteInsert", &CThostFtdcTraderApi::ReqForQuoteInsert)
        .def("ReqQuoteInsert", &CThostFtdcTraderApi::ReqQuoteInsert)
        .def("ReqQuoteAction", &CThostFtdcTraderApi::ReqQuoteAction)
        .def("ReqLockInsert", &CThostFtdcTraderApi::ReqLockInsert)
        .def("ReqCombActionInsert", &CThostFtdcTraderApi::ReqCombActionInsert)
        .def("ReqQryOrder", &CThostFtdcTraderApi::ReqQryOrder)
        .def("ReqQryTrade", &CThostFtdcTraderApi::ReqQryTrade)
        .def("ReqQryInvestorPosition", &CThostFtdcTraderApi::ReqQryInvestorPosition)
        .def("ReqQryTradingAccount", &CThostFtdcTraderApi::ReqQryTradingAccount)
        .def("ReqQryInvestor", &CThostFtdcTraderApi::ReqQryInvestor)
        .def("ReqQryTradingCode", &CThostFtdcTraderApi::ReqQryTradingCode)
        .def("ReqQryInstrumentMarginRate", &CThostFtdcTraderApi::ReqQryInstrumentMarginRate)
        .def("ReqQryInstrumentCommissionRate", &CThostFtdcTraderApi::ReqQryInstrumentCommissionRate)
        .def("ReqQryExchange", &CThostFtdcTraderApi::ReqQryExchange)
        .def("ReqQryProduct", &CThostFtdcTraderApi::ReqQryProduct)
        .def("ReqQryInstrument", &CThostFtdcTraderApi::ReqQryInstrument)
        .def("ReqQryDepthMarketData", &CThostFtdcTraderApi::ReqQryDepthMarketData)
        .def("ReqQrySettlementInfo", &CThostFtdcTraderApi::ReqQrySettlementInfo)
        .def("ReqQryTransferBank", &CThostFtdcTraderApi::ReqQryTransferBank)
        .def("ReqQryInvestorPositionDetail", &CThostFtdcTraderApi::ReqQryInvestorPositionDetail)
        .def("ReqQryNotice", &CThostFtdcTraderApi::ReqQryNotice)
        .def("ReqQrySettlementInfoConfirm", &CThostFtdcTraderApi::ReqQrySettlementInfoConfirm)
        .def("ReqQryInvestorPositionCombineDetail", &CThostFtdcTraderApi::ReqQryInvestorPositionCombineDetail)
        .def("ReqQryCFMMCTradingAccountKey", &CThostFtdcTraderApi::ReqQryCFMMCTradingAccountKey)
        .def("ReqQryEWarrantOffset", &CThostFtdcTraderApi::ReqQryEWarrantOffset)
        .def("ReqQryInvestorProductGroupMargin", &CThostFtdcTraderApi::ReqQryInvestorProductGroupMargin)
        .def("ReqQryExchangeMarginRate", &CThostFtdcTraderApi::ReqQryExchangeMarginRate)
        .def("ReqQryExchangeMarginRateAdjust", &CThostFtdcTraderApi::ReqQryExchangeMarginRateAdjust)
        .def("ReqQryExchangeRate", &CThostFtdcTraderApi::ReqQryExchangeRate)
        .def("ReqQrySecAgentACIDMap", &CThostFtdcTraderApi::ReqQrySecAgentACIDMap)
        .def("ReqQryProductExchRate", &CThostFtdcTraderApi::ReqQryProductExchRate)
        .def("ReqQryProductGroup", &CThostFtdcTraderApi::ReqQryProductGroup)
        .def("ReqQryOptionInstrTradeCost", &CThostFtdcTraderApi::ReqQryOptionInstrTradeCost)
        .def("ReqQryOptionInstrCommRate", &CThostFtdcTraderApi::ReqQryOptionInstrCommRate)
        .def("ReqQryExecOrder", &CThostFtdcTraderApi::ReqQryExecOrder)
        .def("ReqQryForQuote", &CThostFtdcTraderApi::ReqQryForQuote)
        .def("ReqQryQuote", &CThostFtdcTraderApi::ReqQryQuote)
        .def("ReqQryLock", &CThostFtdcTraderApi::ReqQryLock)
        .def("ReqQryLockPosition", &CThostFtdcTraderApi::ReqQryLockPosition)
        .def("ReqQryInvestorLevel", &CThostFtdcTraderApi::ReqQryInvestorLevel)
        .def("ReqQryExecFreeze", &CThostFtdcTraderApi::ReqQryExecFreeze)
        .def("ReqQryCombInstrumentGuard", &CThostFtdcTraderApi::ReqQryCombInstrumentGuard)
        .def("ReqQryCombAction", &CThostFtdcTraderApi::ReqQryCombAction)
        .def("ReqQryTransferSerial", &CThostFtdcTraderApi::ReqQryTransferSerial)
        .def("ReqQryAccountregister", &CThostFtdcTraderApi::ReqQryAccountregister)
        .def("ReqQryContractBank", &CThostFtdcTraderApi::ReqQryContractBank)
        .def("ReqQryParkedOrder", &CThostFtdcTraderApi::ReqQryParkedOrder)
        .def("ReqQryParkedOrderAction", &CThostFtdcTraderApi::ReqQryParkedOrderAction)
        .def("ReqQryTradingNotice", &CThostFtdcTraderApi::ReqQryTradingNotice)
        .def("ReqQryBrokerTradingParams", &CThostFtdcTraderApi::ReqQryBrokerTradingParams)
        .def("ReqQryBrokerTradingAlgos", &CThostFtdcTraderApi::ReqQryBrokerTradingAlgos)
        .def("ReqQueryCFMMCTradingAccountToken", &CThostFtdcTraderApi::ReqQueryCFMMCTradingAccountToken)
        .def("ReqFromBankToFutureByFuture", &CThostFtdcTraderApi::ReqFromBankToFutureByFuture)
        .def("ReqFromFutureToBankByFuture", &CThostFtdcTraderApi::ReqFromFutureToBankByFuture)
        .def("ReqQueryBankAccountMoneyByFuture", &CThostFtdcTraderApi::ReqQueryBankAccountMoneyByFuture)
    ;
}

