#pragma once

class PyCThostFtdcTraderSpi : public CThostFtdcTraderSpi
{
public:
    void OnFrontConnected() override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnFrontConnected, ); }
    void OnFrontDisconnected(int nReason) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnFrontDisconnected, nReason); }
    void OnHeartBeatWarning(int nTimeLapse) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnHeartBeatWarning, nTimeLapse); }
    void OnRspAuthenticate(CThostFtdcRspAuthenticateField * pRspAuthenticateField,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspAuthenticate, pRspAuthenticateField,pRspInfo,nRequestID,bIsLast); }
    void OnRspUserLogin(CThostFtdcRspUserLoginField * pRspUserLogin,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspUserLogin, pRspUserLogin,pRspInfo,nRequestID,bIsLast); }
    void OnRspUserLogout(CThostFtdcUserLogoutField * pUserLogout,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspUserLogout, pUserLogout,pRspInfo,nRequestID,bIsLast); }
    void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField * pUserPasswordUpdate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspUserPasswordUpdate, pUserPasswordUpdate,pRspInfo,nRequestID,bIsLast); }
    void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField * pTradingAccountPasswordUpdate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspTradingAccountPasswordUpdate, pTradingAccountPasswordUpdate,pRspInfo,nRequestID,bIsLast); }
    void OnRspOrderInsert(CThostFtdcInputOrderField * pInputOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspOrderInsert, pInputOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspParkedOrderInsert(CThostFtdcParkedOrderField * pParkedOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspParkedOrderInsert, pParkedOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField * pParkedOrderAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspParkedOrderAction, pParkedOrderAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspOrderAction(CThostFtdcInputOrderActionField * pInputOrderAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspOrderAction, pInputOrderAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField * pQueryMaxOrderVolume,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQueryMaxOrderVolume, pQueryMaxOrderVolume,pRspInfo,nRequestID,bIsLast); }
    void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField * pSettlementInfoConfirm,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspSettlementInfoConfirm, pSettlementInfoConfirm,pRspInfo,nRequestID,bIsLast); }
    void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField * pRemoveParkedOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspRemoveParkedOrder, pRemoveParkedOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField * pRemoveParkedOrderAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspRemoveParkedOrderAction, pRemoveParkedOrderAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspExecOrderInsert(CThostFtdcInputExecOrderField * pInputExecOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspExecOrderInsert, pInputExecOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspExecOrderAction(CThostFtdcInputExecOrderActionField * pInputExecOrderAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspExecOrderAction, pInputExecOrderAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspForQuoteInsert(CThostFtdcInputForQuoteField * pInputForQuote,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspForQuoteInsert, pInputForQuote,pRspInfo,nRequestID,bIsLast); }
    void OnRspQuoteInsert(CThostFtdcInputQuoteField * pInputQuote,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQuoteInsert, pInputQuote,pRspInfo,nRequestID,bIsLast); }
    void OnRspQuoteAction(CThostFtdcInputQuoteActionField * pInputQuoteAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQuoteAction, pInputQuoteAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspLockInsert(CThostFtdcInputLockField * pInputLock,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspLockInsert, pInputLock,pRspInfo,nRequestID,bIsLast); }
    void OnRspCombActionInsert(CThostFtdcInputCombActionField * pInputCombAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspCombActionInsert, pInputCombAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryOrder(CThostFtdcOrderField * pOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryOrder, pOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTrade(CThostFtdcTradeField * pTrade,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTrade, pTrade,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField * pInvestorPosition,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestorPosition, pInvestorPosition,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTradingAccount(CThostFtdcTradingAccountField * pTradingAccount,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTradingAccount, pTradingAccount,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestor(CThostFtdcInvestorField * pInvestor,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestor, pInvestor,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTradingCode(CThostFtdcTradingCodeField * pTradingCode,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTradingCode, pTradingCode,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField * pInstrumentMarginRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInstrumentMarginRate, pInstrumentMarginRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField * pInstrumentCommissionRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInstrumentCommissionRate, pInstrumentCommissionRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExchange(CThostFtdcExchangeField * pExchange,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExchange, pExchange,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryProduct(CThostFtdcProductField * pProduct,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryProduct, pProduct,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInstrument(CThostFtdcInstrumentField * pInstrument,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInstrument, pInstrument,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField * pDepthMarketData,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryDepthMarketData, pDepthMarketData,pRspInfo,nRequestID,bIsLast); }
    void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField * pSettlementInfo,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQrySettlementInfo, pSettlementInfo,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTransferBank(CThostFtdcTransferBankField * pTransferBank,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTransferBank, pTransferBank,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField * pInvestorPositionDetail,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestorPositionDetail, pInvestorPositionDetail,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryNotice(CThostFtdcNoticeField * pNotice,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryNotice, pNotice,pRspInfo,nRequestID,bIsLast); }
    void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField * pSettlementInfoConfirm,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQrySettlementInfoConfirm, pSettlementInfoConfirm,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField * pInvestorPositionCombineDetail,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestorPositionCombineDetail, pInvestorPositionCombineDetail,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField * pCFMMCTradingAccountKey,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryCFMMCTradingAccountKey, pCFMMCTradingAccountKey,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField * pEWarrantOffset,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryEWarrantOffset, pEWarrantOffset,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField * pInvestorProductGroupMargin,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestorProductGroupMargin, pInvestorProductGroupMargin,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField * pExchangeMarginRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExchangeMarginRate, pExchangeMarginRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField * pExchangeMarginRateAdjust,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExchangeMarginRateAdjust, pExchangeMarginRateAdjust,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExchangeRate(CThostFtdcExchangeRateField * pExchangeRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExchangeRate, pExchangeRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField * pSecAgentACIDMap,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQrySecAgentACIDMap, pSecAgentACIDMap,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryProductExchRate(CThostFtdcProductExchRateField * pProductExchRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryProductExchRate, pProductExchRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryProductGroup(CThostFtdcProductGroupField * pProductGroup,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryProductGroup, pProductGroup,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField * pOptionInstrTradeCost,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryOptionInstrTradeCost, pOptionInstrTradeCost,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField * pOptionInstrCommRate,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryOptionInstrCommRate, pOptionInstrCommRate,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExecOrder(CThostFtdcExecOrderField * pExecOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExecOrder, pExecOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryForQuote(CThostFtdcForQuoteField * pForQuote,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryForQuote, pForQuote,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryQuote(CThostFtdcQuoteField * pQuote,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryQuote, pQuote,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryLock(CThostFtdcLockField * pLock,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryLock, pLock,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryLockPosition(CThostFtdcLockPositionField * pLockPosition,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryLockPosition, pLockPosition,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryInvestorLevel(CThostFtdcInvestorLevelField * pInvestorLevel,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryInvestorLevel, pInvestorLevel,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryExecFreeze(CThostFtdcExecFreezeField * pExecFreeze,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryExecFreeze, pExecFreeze,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField * pCombInstrumentGuard,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryCombInstrumentGuard, pCombInstrumentGuard,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryCombAction(CThostFtdcCombActionField * pCombAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryCombAction, pCombAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTransferSerial(CThostFtdcTransferSerialField * pTransferSerial,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTransferSerial, pTransferSerial,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryAccountregister(CThostFtdcAccountregisterField * pAccountregister,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryAccountregister, pAccountregister,pRspInfo,nRequestID,bIsLast); }
    void OnRspError(CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspError, pRspInfo,nRequestID,bIsLast); }
    void OnRtnOrder(CThostFtdcOrderField * pOrder) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnOrder, pOrder); }
    void OnRtnTrade(CThostFtdcTradeField * pTrade) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnTrade, pTrade); }
    void OnErrRtnOrderInsert(CThostFtdcInputOrderField * pInputOrder,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnOrderInsert, pInputOrder,pRspInfo); }
    void OnErrRtnOrderAction(CThostFtdcOrderActionField * pOrderAction,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnOrderAction, pOrderAction,pRspInfo); }
    void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField * pInstrumentStatus) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnInstrumentStatus, pInstrumentStatus); }
    void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField * pTradingNoticeInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnTradingNotice, pTradingNoticeInfo); }
    void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField * pErrorConditionalOrder) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnErrorConditionalOrder, pErrorConditionalOrder); }
    void OnRtnExecOrder(CThostFtdcExecOrderField * pExecOrder) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnExecOrder, pExecOrder); }
    void OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField * pInputExecOrder,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnExecOrderInsert, pInputExecOrder,pRspInfo); }
    void OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField * pExecOrderAction,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnExecOrderAction, pExecOrderAction,pRspInfo); }
    void OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField * pInputForQuote,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnForQuoteInsert, pInputForQuote,pRspInfo); }
    void OnRtnQuote(CThostFtdcQuoteField * pQuote) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnQuote, pQuote); }
    void OnErrRtnQuoteInsert(CThostFtdcInputQuoteField * pInputQuote,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnQuoteInsert, pInputQuote,pRspInfo); }
    void OnErrRtnQuoteAction(CThostFtdcQuoteActionField * pQuoteAction,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnQuoteAction, pQuoteAction,pRspInfo); }
    void OnRtnForQuoteRsp(CThostFtdcForQuoteRspField * pForQuoteRsp) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnForQuoteRsp, pForQuoteRsp); }
    void OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField * pCFMMCTradingAccountToken) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnCFMMCTradingAccountToken, pCFMMCTradingAccountToken); }
    void OnRtnLock(CThostFtdcLockField * pLock) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnLock, pLock); }
    void OnErrRtnLockInsert(CThostFtdcInputLockField * pInputLock,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnLockInsert, pInputLock,pRspInfo); }
    void OnRtnCombAction(CThostFtdcCombActionField * pCombAction) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnCombAction, pCombAction); }
    void OnErrRtnCombActionInsert(CThostFtdcInputCombActionField * pInputCombAction,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnCombActionInsert, pInputCombAction,pRspInfo); }
    void OnRspQryContractBank(CThostFtdcContractBankField * pContractBank,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryContractBank, pContractBank,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryParkedOrder(CThostFtdcParkedOrderField * pParkedOrder,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryParkedOrder, pParkedOrder,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField * pParkedOrderAction,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryParkedOrderAction, pParkedOrderAction,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryTradingNotice(CThostFtdcTradingNoticeField * pTradingNotice,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryTradingNotice, pTradingNotice,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField * pBrokerTradingParams,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryBrokerTradingParams, pBrokerTradingParams,pRspInfo,nRequestID,bIsLast); }
    void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField * pBrokerTradingAlgos,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQryBrokerTradingAlgos, pBrokerTradingAlgos,pRspInfo,nRequestID,bIsLast); }
    void OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField * pQueryCFMMCTradingAccountToken,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQueryCFMMCTradingAccountToken, pQueryCFMMCTradingAccountToken,pRspInfo,nRequestID,bIsLast); }
    void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField * pRspTransfer) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnFromBankToFutureByBank, pRspTransfer); }
    void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField * pRspTransfer) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnFromFutureToBankByBank, pRspTransfer); }
    void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromBankToFutureByBank, pRspRepeal); }
    void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromFutureToBankByBank, pRspRepeal); }
    void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField * pRspTransfer) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnFromBankToFutureByFuture, pRspTransfer); }
    void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField * pRspTransfer) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnFromFutureToBankByFuture, pRspTransfer); }
    void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromBankToFutureByFutureManual, pRspRepeal); }
    void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromFutureToBankByFutureManual, pRspRepeal); }
    void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField * pNotifyQueryAccount) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnQueryBankBalanceByFuture, pNotifyQueryAccount); }
    void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField * pReqTransfer,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnBankToFutureByFuture, pReqTransfer,pRspInfo); }
    void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField * pReqTransfer,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnFutureToBankByFuture, pReqTransfer,pRspInfo); }
    void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField * pReqRepeal,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnRepealBankToFutureByFutureManual, pReqRepeal,pRspInfo); }
    void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField * pReqRepeal,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnRepealFutureToBankByFutureManual, pReqRepeal,pRspInfo); }
    void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField * pReqQueryAccount,CThostFtdcRspInfoField * pRspInfo) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnErrRtnQueryBankBalanceByFuture, pReqQueryAccount,pRspInfo); }
    void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromBankToFutureByFuture, pRspRepeal); }
    void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField * pRspRepeal) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnRepealFromFutureToBankByFuture, pRspRepeal); }
    void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField * pReqTransfer,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspFromBankToFutureByFuture, pReqTransfer,pRspInfo,nRequestID,bIsLast); }
    void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField * pReqTransfer,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspFromFutureToBankByFuture, pReqTransfer,pRspInfo,nRequestID,bIsLast); }
    void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField * pReqQueryAccount,CThostFtdcRspInfoField * pRspInfo,int nRequestID,bool bIsLast) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRspQueryBankAccountMoneyByFuture, pReqQueryAccount,pRspInfo,nRequestID,bIsLast); }
    void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField * pOpenAccount) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnOpenAccountByBank, pOpenAccount); }
    void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField * pCancelAccount) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnCancelAccountByBank, pCancelAccount); }
    void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField * pChangeAccount) override { PYBIND11_OVERLOAD(void, CThostFtdcTraderSpi, OnRtnChangeAccountByBank, pChangeAccount); }

};
class PyCThostFtdcTraderApi : public CThostFtdcTraderApi
{
public:

};
