#ifndef __KSGOLDERROR__H__
#define __KSGOLDERROR__H__

#define KSGOLDERROR_INPUTNULL							1000    //入参为NULL
#define KSGOLDERROR_NOTLOGIN							1001    //客户尚未登录
#define KSGOLDERROR_PARAMETER_EXCEPTION					1002    //发送报文的参数异常
#define KSGOLDERROR_OVERLOAD							1003    //请求超过未处理的请求数
#define KSGOLDERROR_NOTCONNECTGATEWAY					1004    //API未连接网关
#define KSGOLDERROR_ALREADLOGIN							1005    //该客户实例已经登录
#define KSGOLDERROR_PRICEILLEGAL						1006    //输入的价格非法
#define KSGOLDERROR_ORDERREFTOOLOW						1007    //黄金交易平台下单失败[报单引用输入过小]
#define KSGOLDERROR_GATAWAYINITFAIL						1008    //网关初始化失败
#define KSGOLDERROR_ORDERREFSESSIONIDCHECKFAIL			1009    //报单编号和会话ID不匹配
#define KSGOLDERROR_FLOWCONTROLCHECKFAIL				1010	//API流控限制
#define KSGOLDERROR_FIRSTLOGINNEEDMODPWD				1099	//首次登录需要先修改密码
#define KSGOLDERROR_VERSIONCHECKFAIL					-1011   //版本校验失败
#define KSGOLDERROR_TRADERACCOUNTFUND					-1012   //客户账户资金查询失败
#define KSGOLDERROR_USERLOGINEFAIL						-1013   //客户登录失败...
#define KSGOLDERROR_USERLOGOUTFAIL						-1014   //客户录出失败...
#define KSGOLDERROR_SPOTINSTQUERYFAIL					-1015	//现货合约查询失败
#define KSGOLDERROR_TNINSTQUERYFAIL						-1016	//即期T+N合约查询失败
#define KSGOLDERROR_DEFERINSTQUERYFAIL					-1017	//递延合约查询失败
#define KSGOLDERROR_DELIVERYCODEQUERYFAIL				-1018	//交割品种查询失败
#define KSGOLDERROR_INSTCACHNOTEXIST					-1019	//缓存的合约信息不存在
#define KSGOLDERROR_INSTNOTFOUND						-1020	//未查询到对应的合约信息
#define KSGOLDERROR_DELIVERYCODECACHNOTEXIST			-1021	//缓存的交割品种信息不存在
#define KSGOLDERROR_DELIVERYCODENOTFOUND				-1022	//未查询到对应的交割品种信息
#define KSGOLDERROR_INITORDERQUERYERROR					-1023	//初始化委托查询失败
#define KSGOLDERROR_INITDONEQUERYERROR					-1024	//初始化成交查询失败
#define KSGOLDERROR_INITDONEQUERYGETNEXTERROR			-1025	//初始化委托查询取后续包出错
#define KSGOLDERROR_INITORDERQUERYGETNEXTERROR			-1026	//初始化成交查询取后续包出错 
#define KSGOLDERROR_QUERYCONNECTIONLOGINFAIL			-1027	//查询连接登录失败...
#define KSGOLDERROR_ORDERACTIONFAIL						-1028	//普通撤单请求条件不满足...
#define KSGOLDERROR_CONDITIONORDERACTIONFAIL			-1029   //条件单撤单请求条件不满足,条件单号不能为空
#define KSGOLDERROR_SUBMARKETDATAOPERATORFAIL			-1030   //行情订阅/退订操作失败
#define KSGOLDERROR_QUERYRECORDNOTFOUND					-1031   //查无记录

#endif  //__KSGOLDERROR__H__