__OES_ORD_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "mktId": "uint8",
    "ordType": "uint8",
    "bsType": "uint8",
    "__ORD_BASE_INFO_filler": "uint8",
    "invAcctId": "string",
    "securityId": "string",
    "ordQty": "int32",
    "ordPrice": "int32",
    "origClOrdId": "int64",
}
__OES_ORD_CANCEL_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "mktId": "uint8",
    "__ORD_CANCEL_BASE_INFO_filler1": "uint8",
    "invAcctId": "string",
    "securityId": "string",
    "origClSeqNo": "int32",
    "origClEnvId": "int8",
    "__ORD_CANCEL_BASE_INFO_filler2": "uint8",
    "origClOrdId": "int64",
}
__OES_ORD_REQ_LATENCY_FIELDS_IMPL = {
    "__ordReqOrigSendTime": "STimeval32T",
}
__OES_ORD_CNFM_LATENCY_FIELDS_IMPL = {
    "__ordReqOrigRecvTime": "STimeval32T",
    "__ordReqCollectedTime": "STimeval32T",
    "__ordReqActualDealTime": "STimeval32T",
    "__ordReqProcessedTime": "STimeval32T",
    "__ordCnfmOrigRecvTime": "STimeval32T",
    "__ordCnfmCollectedTime": "STimeval32T",
    "__ordCnfmActualDealTime": "STimeval32T",
    "__ordCnfmProcessedTime": "STimeval32T",
    "__ordDeclareTime": "STimeval32T",
    "__ordDeclareDoneTime": "STimeval32T",
    "__pushingTime": "STimeval32T",
}
__OES_ORD_CNFM_BASE_INFO_PKT = {
    "__OES_ORD_BASE_INFO_PKT": "dict",
    "__OES_ORD_REQ_LATENCY_FIELDS": "dict",
    "clOrdId": "int64",
    "clientId": "int16",
    "clEnvId": "int8",
    "origClEnvId": "int8",
    "origClSeqNo": "int32",
    "ordDate": "int32",
    "ordTime": "int32",
    "ordCnfmTime": "int32",
    "ordStatus": "uint8",
    "ordCnfmSts": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "__platformId": "uint8",
    "__tgwGrpNo": "uint8",
    "__tgwPartitionNo": "uint8",
    "productType": "uint8",
    "exchOrdId": "string",
    "__declareFlag": "uint8",
    "__repeatFlag": "uint8",
    "ownerType": "uint8",
    "frzAmt": "int64",
    "frzInterest": "int64",
    "frzFee": "int64",
    "cumAmt": "int64",
    "cumInterest": "int64",
    "cumFee": "int64",
    "cumQty": "int32",
    "canceledQty": "int32",
    "ordRejReason": "int32",
    "exchErrCode": "int32",
    "pbuId": "int32",
    "branchId": "int32",
    "__rowNum": "int32",
    "__recNum": "uint32",
    "__OES_ORD_CNFM_LATENCY_FIELDS": "dict",
}
__OES_ORD_CNFM_EXT_INFO_PKT = {
    "frzMargin": "int64",
    "cumMargin": "int64",
    "__ORD_CNFM_EXT_reserve": "string",
}
__OES_TRD_BASE_INFO_PKT = {
    "exchTrdNum": "int64",
    "mktId": "uint8",
    "trdSide": "uint8",
    "__platformId": "uint8",
    "__trdCnfmType": "uint8",
    "__etfTrdCnfmSeq": "uint32",
    "invAcctId": "string",
    "securityId": "string",
    "trdDate": "int32",
    "trdTime": "int32",
    "trdQty": "int32",
    "trdPrice": "int32",
    "trdAmt": "int64",
    "clOrdId": "int64",
    "cumQty": "int32",
    "__rowNum": "int32",
    "__tgwGrpNo": "uint8",
    "__isTrsfInCashAvailable": "uint8",
    "__tgwPartitionNo": "uint8",
    "productType": "uint8",
    "origOrdQty": "int32",
    "pbuId": "int32",
    "branchId": "int32",
}
__OES_TRD_BASE_LATENCY_FIELDS = {
    "__trdCnfmOrigRecvTime": "STimeval32T",
    "__trdCnfmCollectedTime": "STimeval32T",
    "__trdCnfmActualDealTime": "STimeval32T",
    "__trdCnfmProcessedTime": "STimeval32T",
    "__pushingTime": "STimeval32T",
}
__OES_TRD_CNFM_BASE_INFO_PKT = {
    "__OES_TRD_BASE_INFO_PKT": "dict",
    "clSeqNo": "int32",
    "clientId": "int16",
    "clEnvId": "int8",
    "subSecurityType": "uint8",
    "ordStatus": "uint8",
    "ordType": "uint8",
    "ordBuySellType": "uint8",
    "securityType": "uint8",
    "origOrdPrice": "int32",
    "cumAmt": "int64",
    "cumInterest": "int64",
    "cumFee": "int64",
    "__OES_TRD_CNFM_LATENCY_FIELDS": "dict",
}
__OES_TRD_CNFM_EXT_INFO_PKT = {
    "trdInterest": "int64",
    "trdFee": "int64",
    "trdMargin": "int64",
    "cumMargin": "int64",
    "__TRD_CNFM_EXT_reserve": "string",
}
__OES_LOT_WINNING_BASE_INFO_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "lotType": "uint8",
    "rejReason": "uint8",
    "__LOT_WINNING_BASE_INFO_filler": "int8",
    "lotDate": "int32",
    "securityName": "string",
    "assignNum": "int64",
    "lotQty": "int32",
    "lotPrice": "int32",
    "lotAmt": "int64",
}
__OES_FUND_TRSF_BASE_INFO_PKT = {
    "clSeqNo": "int32",
    "direct": "uint8",
    "isAllotOnly": "uint8",
    "__FUND_TRSF_BASE_filler": "uint8",
    "cashAcctId": "string",
    "trdPasswd": "string",
    "trsfPasswd": "string",
    "occurAmt": "int64",
}
__OES_ISSUE_BASE_INFO_PKT = {
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "isCancelAble": "uint8",
    "isReApplyAble": "uint8",
    "productType": "uint8",
    "suspFlag": "uint8",
    "issueType": "uint8",
    "securityName": "string",
    "underlyingSecurityId": "string",
    "startDate": "int32",
    "endDate": "int32",
    "issueQty": "int64",
    "qtyUnit": "int32",
    "ordMaxQty": "int32",
    "ordMinQty": "int32",
    "issuePrice": "int32",
    "upperLimitPrice": "int32",
    "ceilPrice": "int32",
    "lowerLimitPrice": "int32",
    "floorPrice": "int32",
}
__OES_STOCK_BASE_INFO_PKT = {
    "securityId": "string",
    "mktId": "uint8",
    "productType": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "securityLevel": "uint8",
    "securityRiskLevel": "uint8",
    "currType": "uint8",
    "qualificationClass": "uint8",
    "isDayTrading": "uint8",
    "suspFlag": "uint8",
    "temporarySuspFlag": "uint8",
    "__STOCK_BASE_filler": "uint8",
    "buyQtyUnit": "int32",
    "lmtBuyMaxQty": "int32",
    "buyOrdMaxQty": "int32",
    "lmtBuyMinQty": "int32",
    "buyOrdMinQty": "int32",
    "mktBuyMaxQty": "int32",
    "mktBuyMinQty": "int32",
    "sellQtyUnit": "int32",
    "lmtSellMaxQty": "int32",
    "sellOrdMaxQty": "int32",
    "lmtSellMinQty": "int32",
    "sellOrdMinQty": "int32",
    "mktSellMaxQty": "int32",
    "mktSellMinQty": "int32",
    "priceTick": "int32",
    "priceUnit": "int32",
    "prevClose": "int32",
    "parPrice": "int64",
    "bondInterest": "int64",
    "repoExpirationDays": "int32",
    "cashHoldDays": "int32",
    "priceLimit": "OesPriceLimitT",
    "securityName": "string",
    "fundId": "string",
    "outstandingShare": "int64",
    "publicFloatShare": "int64",
    "__STOCK_BASE_reserve": "string",
}
__OES_ETF_BASE_INFO_PKT = {
    "fundId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "isPublishIOPV": "uint8",
    "isCreationAble": "uint8",
    "isRedemptionAble": "uint8",
    "isDisabled": "uint8",
    "__ETF_BASE_filler": "uint8",
    "componentCnt": "int32",
    "creRdmUnit": "int32",
    "maxCashRatio": "int32",
    "nav": "int32",
    "navPerCU": "int64",
    "dividendPerCU": "int64",
    "tradingDay": "int32",
    "preTradingDay": "int32",
    "estiCashCmpoent": "int64",
    "cashCmpoent": "int64",
    "creationLimit": "int64",
    "redemLimit": "int64",
    "netCreationLimit": "int64",
    "netRedemLimit": "int64",
}
__OES_ETF_COMPONENT_BASE_INFO_PKT = {
    "fundId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "subFlag": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "prevClose": "int32",
    "qty": "int32",
    "premiumRate": "int32",
    "creationSubCash": "int64",
    "redemptionCashSub": "int64",
}
__OES_CASH_ASSET_BASE_INFO_PKT = {
    "cashAcctId": "string",
    "custId": "string",
    "currType": "uint8",
    "cashType": "uint8",
    "cashAcctStatus": "uint8",
    "isFundTrsfDisabled": "uint8",
    "__CASH_ASSET_BASE_filler": "uint8",
    "beginningBal": "int64",
    "beginningAvailableBal": "int64",
    "beginningDrawableBal": "int64",
    "disableBal": "int64",
    "reversalAmt": "int64",
    "manualFrzAmt": "int64",
    "totalDepositAmt": "int64",
    "totalWithdrawAmt": "int64",
    "withdrawFrzAmt": "int64",
    "totalSellAmt": "int64",
    "totalBuyAmt": "int64",
    "buyFrzAmt": "int64",
    "totalFeeAmt": "int64",
    "feeFrzAmt": "int64",
    "marginAmt": "int64",
    "marginFrzAmt": "int64",
}
__OES_CASH_ASSET_EXT_INFO_PKT = {
    "currentTotalBal": "int64",
    "currentAvailableBal": "int64",
    "currentDrawableBal": "int64",
    "{": "struct",
    "initialMargin": "int64",
    "totalExerciseFrzAmt": "int64",
    "pendingSupplMargin": "int64",
    "sseAvailablePurchaseLimit": "int64",
    "szseAvailablePurchaseLimit": "int64",
    "totalMarketMargin": "int64",
    "totalNetMargin": "int64",
    "optionExt": "}",
    "__CASH_ASSET_EXT_reserve": "string",
}
__OES_CUST_BASE_INFO_PKT = {
    "custId": "string",
    "custType": "uint8",
    "status": "uint8",
    "riskLevel": "uint8",
    "originRiskLevel": "uint8",
    "institutionFlag": "uint8",
    "investorClass": "uint8",
    "optSettlementCnfmFlag": "uint8",
    "__CUST_BASE_filler1": "uint8",
    "branchId": "int32",
    "__CUST_BASE_filler2": "uint32",
}
__OES_INV_ACCT_BASE_INFO_PKT = {
    "invAcctId": "string",
    "mktId": "uint8",
    "acctType": "uint8",
    "status": "uint8",
    "ownerType": "uint8",
    "optInvLevel": "uint8",
    "isTradeDisabled": "uint8",
    "__INV_ACCT_BASE_filler": "uint8",
    "limits": "uint64",
    "permissions": "uint64",
    "pbuId": "int32",
    "stkPositionLimitRatio": "int32",
    "subscriptionQuota": "int32",
    "kcSubscriptionQuota": "int32",
    "__INV_ACCT_BASE_reserve": "string",
}
__OES_STK_HOLDING_BASE_INFO_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "productType": "uint8",
    "__HOLD_BASE_filler": "uint8",
    "originalHld": "int64",
    "originalCostAmt": "int64",
    "totalBuyHld": "int64",
    "totalSellHld": "int64",
    "sellFrzHld": "int64",
    "manualFrzHld": "int64",
    "totalBuyAmt": "int64",
    "totalSellAmt": "int64",
    "totalBuyFee": "int64",
    "totalSellFee": "int64",
    "totalTrsfInHld": "int64",
    "totalTrsfOutHld": "int64",
    "trsfOutFrzHld": "int64",
    "originalLockHld": "int64",
    "totalLockHld": "int64",
    "totalUnlockHld": "int64",
    "originalAvlHld": "int64",
    "maxReduceQuota": "int64",
}
__OES_STK_HOLDING_EXT_INFO_PKT = {
    "sellAvlHld": "int64",
    "trsfOutAvlHld": "int64",
    "lockAvlHld": "int64",
    "__filler": "int64",
    "sumHld": "int64",
    "costPrice": "int64",
}
__OES_NOTIFY_BASE_INFO_PKT = {
    "notifySeqNo": "int32",
    "notifySource": "uint8",
    "notifyType": "uint8",
    "notifyLevel": "uint8",
    "notifyScope": "uint8",
    "tranTime": "int32",
    "__NOTIFY_INFO_filler": "int32",
    "custId": "string",
    "content": "string",
}
__OES_OPTION_BASE_INFO_PKT = {
    "securityId": "string",
    "mktId": "uint8",
    "productType": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "contractType": "uint8",
    "exerciseType": "uint8",
    "deliveryType": "uint8",
    "isDayTrading": "uint8",
    "limitOpenFlag": "uint8",
    "suspFlag": "uint8",
    "temporarySuspFlag": "uint8",
    "__OPTION_BASE_filler1": "uint8",
    "contractUnit": "int32",
    "exercisePrice": "int32",
    "deliveryDate": "int32",
    "deliveryMonth": "int32",
    "listDate": "int32",
    "lastTradeDay": "int32",
    "exerciseBeginDate": "int32",
    "exerciseEndDate": "int32",
    "contractPosition": "int64",
    "prevClosePrice": "int32",
    "prevSettlPrice": "int32",
    "underlyingClosePrice": "int32",
    "priceTick": "int32",
    "upperLimitPrice": "int32",
    "lowerLimitPrice": "int32",
    "buyQtyUnit": "int32",
    "lmtBuyMaxQty": "int32",
    "lmtBuyMinQty": "int32",
    "mktBuyMaxQty": "int32",
    "mktBuyMinQty": "int32",
    "sellQtyUnit": "int32",
    "lmtSellMaxQty": "int32",
    "lmtSellMinQty": "int32",
    "mktSellMaxQty": "int32",
    "mktSellMinQty": "int32",
    "sellMargin": "int64",
    "originalSellMargin": "int64",
    "marginRatioParam1": "int32",
    "marginRatioParam2": "int32",
    "increasedMarginRatio": "int32",
    "expireDays": "int32",
    "contractId": "string",
    "securityName": "string",
    "securityStatusFlag": "string",
    "underlyingSecurityId": "string",
    "underlyingMktId": "uint8",
    "underlyingSecurityType": "uint8",
    "__OPTION_BASE_filler3": "uint8",
    "__OPTION_BASE_reserve": "string",
}
__OES_OPT_HOLDING_BASE_INFO_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "positionType": "uint8",
    "productType": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "contractType": "uint8",
    "hedgeFlag": "uint8",
    "__HOLD_BASE_filler": "uint8",
    "originalQty": "int64",
    "originalAvlQty": "int64",
    "originalCostAmt": "int64",
    "originalCarryingAmt": "int64",
    "totalOpenQty": "int64",
    "uncomeQty": "int64",
    "totalCloseQty": "int64",
    "closeFrzQty": "int64",
    "manualFrzQty": "int64",
    "totalInPremium": "int64",
    "totalOutPremium": "int64",
    "totalOpenFee": "int64",
    "totalCloseFee": "int64",
    "exerciseFrzQty": "int64",
    "positionMargin": "int64",
    "__OPT_HOLDING_BASE_reserve": "string",
}
__OES_OPT_HOLDING_EXT_INFO_PKT = {
    "closeAvlQty": "int64",
    "exerciseAvlQty": "int64",
    "sumQty": "int64",
    "costPrice": "int64",
    "carryingAvgPrice": "int64",
    "coveredAvlUnderlyingQty": "int64",
    "availableLongPositionLimit": "int32",
    "availableTotalPositionLimit": "int32",
    "availableDailyBuyOpenLimit": "int32",
    "__OPT_HOLDING_EXT_filler2": "int32",
    "__OPT_HOLDING_EXT_reserve": "string",
}
__OES_OPT_UNDERLYING_HOLDING_BASE_PKT = {
    "invAcctId": "string",
    "underlyingSecurityId": "string",
    "mktId": "uint8",
    "underlyingMktId": "uint8",
    "underlyingSecurityType": "uint8",
    "underlyingSubSecurityType": "uint8",
    "__OPT_UNDERLYING_HOLD_BASE_filler": "uint8",
    "originalHld": "int64",
    "originalAvlHld": "int64",
    "originalCoveredQty": "int64",
    "initialCoveredQty": "int64",
    "coveredQty": "int64",
    "coveredGapQty": "int64",
    "coveredAvlQty": "int64",
    "lockAvlQty": "int64",
    "sumHld": "int64",
    "maxReduceQuota": "int64",
}
__OES_OPTION_POSITION_LIMIT_BASE_PKT = {
    "invAcctId": "string",
    "underlyingSecurityId": "string",
    "mktId": "uint8",
    "underlyingMktId": "uint8",
    "underlyingSecurityType": "uint8",
    "underlyingSubSecurityType": "uint8",
    "__POSITION_LIMIT_BASE_filler1": "uint8",
    "longPositionLimit": "int32",
    "totalPositionLimit": "int32",
    "dailyBuyOpenLimit": "int32",
    "__POSITION_LIMIT_BASE_filler2": "int32",
    "originalLongQty": "int32",
    "totalBuyOpenQty": "int32",
    "uncomeBuyOpenQty": "int32",
    "totalSellCloseQty": "int32",
    "originalShortQty": "int32",
    "totalSellOpenQty": "int32",
    "uncomeSellOpenQty": "int32",
    "totalBuyCloseQty": "int32",
    "originalCoveredQty": "int32",
    "totalCoveredOpenQty": "int32",
    "uncomeCoveredOpenQty": "int32",
    "totalCoveredCloseQty": "int32",
}
__OES_OPTION_EXERCISE_ASSIGN_BASE_PKT = {
    "invAcctId": "string",
    "securityId": "string",
    "mktId": "uint8",
    "positionType": "uint8",
    "productType": "uint8",
    "securityType": "uint8",
    "subSecurityType": "uint8",
    "contractType": "uint8",
    "deliveryType": "uint8",
    "__OPTION_EXERCISE_ASSIGN_filler1": "uint8",
    "exercisePrice": "int32",
    "exerciseQty": "int32",
    "deliveryQty": "int64",
    "exerciseBeginDate": "int32",
    "exerciseEndDate": "int32",
    "clearingDate": "int32",
    "deliveryDate": "int32",
    "clearingAmt": "int64",
    "clearingFee": "int64",
    "settlementAmt": "int64",
    "underlyingSecurityId": "string",
    "underlyingMktId": "uint8",
    "underlyingSecurityType": "uint8",
    "__OPTION_EXERCISE_ASSIGN_filler3": "uint8",
    "securityName": "string",
    "__OPTION_EXERCISE_ASSIGN_reserve": "string",
}
__OES_OPT_SETTLEMENT_CONFIRM_BASE_PKT = {
    "custId": "string",
    "clientId": "int16",
    "clEnvId": "int8",
    "__filler2": "int8",
    "transDate": "int32",
    "transTime": "int32",
    "rejReason": "int32",
    "__OPT_SETTLEMENT_CONFIRM_BASE_reserve": "string",
}
__OES_ORD_REQ_LATENCY_FIELDS = __OES_ORD_REQ_LATENCY_FIELDS_IMPL
__OES_ORD_CNFM_LATENCY_FIELDS = __OES_ORD_CNFM_LATENCY_FIELDS_IMPL
__OES_TRD_CNFM_LATENCY_FIELDS = __OES_TRD_BASE_LATENCY_FIELDS
